NEWS.md, pom.xml, src/main/resources/templates/db_scripts/schema.json
As using outer joins impedes performance and for filtering only is not required
=> Make instance and holdings view an inner join again MODINVSTOR-55

ramls/instance.json
It's was in the wrong place, and the unique constraint does not seem to be enforced for arrays of objects anyway. 
This clean-up of obsolete code does not change the API in any way.
=> Remove non-functional uniqueItems constraint. MODINVSTOR-86.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/holdings-storage.raml, ramls/holdingsrecord.json, ramls/item-storage.raml, ramls/item.json, ramls/loan-type.raml, ramls/loantype.json, ramls/material-type.raml, ramls/materialtype.json, src/main/resources/templates/db_scripts/schema.json
[STCOM-228](https://issues.folio.org/browse/STCOM-228), [UIIN-98](https://issues.folio.org/browse/UIIN-98) and [UIIN-99](https://issues.folio.org/browse/UIIN-98) need update `metadata` added to the payloads they fetch. There will need to be one more PR against `mod-inventory` to add metadata to the `/inventory/items` endpoint.
I'm using PR #53 as my guide with this implementation but let me know if there's anything I could be doing better here, please. 
I also bumped minor version numbers on the APIs since we're adding functionality (but mostly bc @marc-johnson did it in that PR 😝).
=> MODINVSTOR-71: Added metadata to holdings, items, loan types and material types

.gitignore
We changed the directory where we write generated sources. Now there are below target/generated_sources/ .
Therefore we no longer need src/main/**/client/ in .gitignore
=> MODINVSTOR-120: Drop src/main/**/client/ from .gitignore

src/main/java/org/folio/rest/impl/InstanceStorageAPI.java
private boolean blankTenantId(String tenantId) is not used and has a wrong String comparator.
=> MODINVSTOR-140: Remove InstanceStorage.blankTenantId(String)

NEWS.md, pom.xml, src/test/java/org/folio/rest/api/ContributorTypesTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/http/InterfaceUrls.java
https://issues.folio.org/browse/MODINVSTOR-164
The shared RAML had been incorrectly moved back to an older version which disallowed page limit parameters higher than 100.
This change reverts to the same shared RAML as version 12.6.0
=> Move shared raml back to previous version MODINVSTOR-164

NEWS.md, pom.xml
Use the just released RMB 19.4.3, and indirectly cql2pgjson 2.2.2, which use the 'simple' directory for fulltext searches.
=> Modinvstor 168 simple

ramls/holdingsrecord.json, ramls/instance.json, ramls/item.json
We are using FOLIO extensions to JSON Schema, as described at https://github.com/folio-org/mod-graphql/blob/master/src/autogen/README.md#option-1-json-schema-extensions, to indiciate when one record can link to another -- e.g. an instance record can link to its holdings. These fields are safely ignored by RMB, but interpreted by mod-graphql.
Similarly, we use "weak" references when creating cycles: `folio:$ref` rather than the standard `$ref`. Again, mod-graphql knows to follow these; but RMB does not, which is good, because it can't handle the cycles that they create (e.g. instance -> holdings -> items -> holding -> instance).
=> Add links that can be traversed by mod-graphql

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/servicepoint.json, src/test/java/org/folio/rest/api/ServicePointTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
Added an array `staffSlips` to the service point schema. This array accepts 2 properties, the `id` of the staff slip and `printByDefault` boolean property which will be used to determine the default print behavior for the slip.
Also, increased the reference data timeout to 30 seconds, since this timeout was too low for my dev machine and the builds failed consistently at 20 seconds.
=> Implement MODINVSTOR-235: add print by default property to service point

pom.xml, ramls/instance-storage.raml, src/main/java/org/folio/rest/impl/InstanceStorageAPI.java, src/main/java/org/folio/rest/impl/StorageHelper.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
* Speed up PUT /instance-storage/instances/{instanceId} by using PgUtil.put.
* Fix 404 for PUT /instance-storage/instances/{instanceId}.
* Remove duplicated code for deleting source record by using PgUtil.deleteById.
* Update RMB to v23.4.0, needed for PgUtil.put.
* Deprecate StorageHelper methods that have been moved to RMB PgUtil.
=> MODINVSTOR-254: Performance: PUT /instance-storage/instances/{instId}

src/test/java/org/folio/rest/api/InstanceStorageTest.java
canGetAllInstances unit test may fail because the database returns the records unsorted.
=> MODINVSTOR-215: Fix sorting of canGetAllInstances

pom.xml, src/test/java/org/folio/rest/api/ItemStorageTest.java
When mod-inventory-storage was upgraded to RAML module builder 23.4.0 it lost the ability to search when an item ID does not match a value.
This was [resolved](https://issues.folio.org/browse/CQLPG-86) and released in [cql2pgjson 3.10.0](https://github.com/folio-org/cql2pgjson-java/releases/tag/v3.1.0) [RAML Module Builder 23.6.0](https://github.com/folio-org/raml-module-builder/releases/tag/v23.6.0)
This pull request adds a test to replicate the failing behaviour and the resolution.
=> Fix searching by barcode and not specific record MODINVSTOR-267 

reference-data/service-points/cd1.json, reference-data/service-points/cd2.json
It is frustrating to need to edit the service points to make them available for pickup each time, as this is required in order to create a fulfillable request.
Hence, let's make the reference service points available for pickup.
=> Make sample service points available for pickup MODINVSTOR-268

src/main/resources/templates/db_scripts/schema.json
Adjust barcode index so SQL generated by {{query=(barcode==123)}} can leverage. Remove lower/accent should be fine since we have full text index (and gin index) on barcode field as well. Performance test (50 requests in 50 seconds) shows that the change can improve {{query-by-barcode}} (~8s to ~100ms) and related parent APIs ({{checkin/out-by-barcode}} for example, ~25s to ~1s) significantly.
=> MODINVSTOR-269: barcode==123 does not perform

reference-data/instance-statuses/notyetassigned.json, sample-data/holdingsrecords/aba-holdingsrecord3.json, sample-data/instances/american-journal-of-medicine.json
While investigating mod-inventory-storage API test failures, it was noticed that 
- two sample data records use "null" values that break JSON schema validation. 
-- null statisticalCodeId. See https://github.com/folio-org/mod-inventory-storage/blob/v15.5.1/sample-data/holdingsrecords/aba-holdingsrecord3.json#L29
-- null notes. See https://github.com/folio-org/mod-inventory-storage/blob/v15.5.1/sample-data/instances/american-journal-of-medicine.json#L44
- one reference data uses "null" as instance status code.
-- null instance status code. See https://github.com/folio-org/mod-inventory-storage/blob/v15.5.1/reference-data/instance-statuses/notyetassigned.json#L3
This PR **removed** null values from sample data and **changed "null" to "none"** in reference data.
=> Remove null from reference and sample data

CODEOWNERS
As the ThunderJet team are conducting some work in inventory, the technical leads of this team should be added to the code owners, in order to facilitate expediting of changes when necessary
=> Make Craig and Piotr Code Owners

descriptors/ModuleDescriptor-template.json, ramls/examples/holdingsrecord_get.json, ramls/examples/holdingsrecords_get.json, ramls/holdings-storage.raml, ramls/holdingsrecord.json, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java, src/test/java/org/folio/rest/support/builders/JsonRequestBuilder.java
Due to https://issues.folio.org/browse/MODINVSTOR-324 we would like to introduce tags for holdingentities.
* update holding model with tags
* update holding interfaces versions
* update tests
=> MODINVSTOR-324 Inventory App: Assign tags to holdings record

pom.xml
RMB 26.3.1 has a fix that should "restore" to acceptable performance
for full-text queries. RMB-455
=> Update to RMB 26.3.1

src/main/java/org/folio/rest/impl/HoldingsTypeAPI.java, src/test/java/org/folio/rest/api/HoldingsTypeTest.java, src/test/java/org/folio/rest/api/ReferenceTablesTest.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
Resolves: MODINVSTOR-318
Controlled Vocab Duplicate Issues (Holdings Type and Call Number type) Change server response for errors during loan type creation.
https://issues.folio.org/browse/MODINVSTOR-318
=> [MODINVSTOR-318] Respond 422 on post holdings type with duplicate name

src/test/java/org/folio/rest/api/SampleDataTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
Reusing the completed Future for running the second post tenant
starts the second post tenant that inserts all the sample records
but because of the completed Future it doesn't wait until they
are inserted but immediately returns to start running the other tests.
The other tests fail because records are inserted in parallel.
Use a new (uncompleted) Future to wait until the second post tenant
has completed before starting the other unit tests.
=> MODINVSTOR-271: Unit tests can fail on ref constraint violations.

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/holdingsrecord.json, ramls/item-storage.raml, ramls/item.json, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/support/ResponseUtil.java, src/main/resources/templates/db_scripts/itemEffectiveLocation.sql, src/main/resources/templates/db_scripts/populateEffectiveLocationForExistingItems.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTestDataProvider.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/LoanTypeTest.java, src/test/java/org/folio/rest/api/LocationsTest.java, src/test/java/org/folio/rest/api/MaterialTypeTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/ResponseUtilTest.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
Add set of triggers (for item and holdings_record tables) to persist effectiveLocation for item.
**Logic to calculate item effectiveLocation:**
First not null:
1. Item temporaryLocation;
2. Item permanentLocation;
3. Holding record temporaryLocation;
4. Holding record permanentLocation;
**Holding records trigger implementation details**:
* Updates related items only if following properties have changed: 
* temporaryLocationId; 
* permanentLocationId;
* Only those items are updated which has no value for their's permanent or temporary locations because otherwise the update won't take any affect.
**Item trigger implementation details:**
* Item effective location is re-calculated only if following properties changed: 
* temporaryLocationId; 
* permanentLocationId;
* holdingsRecordId.
Related …
=> MODINVSTOR-348: Calculate and persist effective location for item.

src/main/java/org/folio/rest/impl/InstanceStorageBatchAPI.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
Expected:
When the instance is first created by data-import, the create/update date/time should be the same, and roughly equivalent to the "ended running" date/time in the import log.
When the instance is updated, the update date/time should change to be a few minutes later, but the create date/time should stay the same.
Actual:
When the instance is first created by data-import, the create/update date/time shows as unknown
When the instance is updated, the update date/time and the create date/time both change to the updated time
=> MODINVSTOR-387 Admin data not updating properly on Instances created from SRS

descriptors/ModuleDescriptor-template.json, ramls/item-storage.raml, ramls/item.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
Store the information about when, where and by whom an item was last checked in, even when there is no loan.
This data is to be displayed in the item details.
This resolves MODINVSTOR-386
To be used in UIIN-749
=> MODINVSTOR-386: Add last checkin properties

src/main/resources/templates/db_scripts/instanceStatusUpdatedDateTrigger.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/IndividualResource.java, src/test/java/org/folio/rest/support/matchers/DateTimeMatchers.java
https://issues.folio.org/browse/MODINVSTOR-376: Instance record. Status updated date does not populate in detailed view
Added new before update trigger for instance table that sets `statusUpdatedDate` = NOW in case instance's `statusId` property has been changed.
The date time in `statusUpdatedDate` has the following format `yyyy-MM-dd'T'HH:mm:ss.SSS` (ISO-8601 that is standard in java) and it is in UTC timezone.
=> MODINVSTOR-376: Handle statusUpdatedDate property for instance.

ramls/item-storage.raml, ramls/item.json, src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/resources/templates/db_scripts/holdingsRecordHrid.sql, src/main/resources/templates/db_scripts/instanceHrid.sql, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
Adds effectiveCallNumber property to Item and logic to derive its value on CREATE and PUT.
effectiveCallNumber will be set to:
- itemLevelCallNumber, if it is present on the Item
- If itemLevelCallNumber is not present and the Item has a holdingsRecordId, the matching holdingsRecord will be retrieved and effectiveCallNumber will be set to its value.
=> [MODINVSTOR 357] Store effective call number on item record

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODINVSTOR-396 FOLIO-2358 manage container memory

src/main/resources/templates/db_scripts/instanceStatusUpdatedDateTrigger.sql, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/support/matchers/DateTimeMatchers.java
https://issues.folio.org/browse/MODINVSTOR-376 - Instance record. Status updated date does not populate in detailed view.
Previously `statusUpdatedDate` was returned with no time zone information, which causes UI to display it in a wrong time zone. 
This PR changes `statusUpdatedDate` to has `yyyy-MM-dd'T'HH:mm:ss.SSS'+0000'` pattern (the same that used for metadata fields).
=> [BUGFIX] MODINVSTOR-376: Fix date time format.

src/main/resources/templates/db_scripts/updateItemStatusDate.sql, src/test/java/org/folio/rest/api/ItemStorageTest.java
Bugfix regarding item status date at the "item" object:
Time Zone didn't exist in this field.
=> [BUGFIX]: MODINVSTOR-367: Maintain item status date even if item record is edited

sample-data/holdingsrecords/aba-holdingsrecord4.json, src/main/java/org/folio/rest/impl/HoldingsBatchSyncAPI.java, src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java, src/main/java/org/folio/rest/support/HridManager.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/HridSettingsStorageTest.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
When creating holdings records set a generated HRID when not present.
When modifying holdings records ensure the HRID cannot be changed.
=> MODINVSTOR-374: Add holdings HRID support

src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
When creating items set a generated HRID when not present.
When modifying items ensure the HRID cannot be changed.
Note: also removed some existing code smells with simple, minimal risk, changes in `ItemStorageAPI.java` which is why there are a couple of seemingly unrelated code changes.
=> MODINVSTOR-375: Add item HRID support

pom.xml
There have been numerous breaking compatibility changes since the last release, these have not been reflected in the implementation version
=> MODINVSTOR-402 Change version to 18.0.0

quick-test.sh, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/matchers/PostgresErrorMessageMatchers.java
The error messages produced by PostgreSQL vary by version, meaning that the build could fail using a PostgreSQL server to the one used by embedded PostgreSQL.
This even occurs within the same major version (the line number reference differs).
This pull request weakens the check on the error message, to not include the line number or the maximum value of the sequence.
=> MODINVSTOR-405 weaken HRID error message checks

descriptors/ModuleDescriptor-template.json, pom.xml, ramls/hrid-settings-storage.raml, ramls/hridsetting.json, src/main/java/org/folio/rest/support/HridManager.java, src/main/resources/templates/db_scripts/alterHridSequences.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/HridSettingsIncreaseMaxValueMigrationTest.java, src/test/java/org/folio/rest/api/HridSettingsStorageParameterizedTest.java, src/test/java/org/folio/rest/api/HridSettingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/TestBase.java
https://issues.folio.org/browse/MODINVSTOR-410: Increase digits for Inventory Instance HRIDs
https://issues.folio.org/browse/MODINVSTOR-411: Increase digits for Inventory Holdings HRIDs
https://issues.folio.org/browse/MODINVSTOR-412: Increase digits for Inventory Item HRIDs
https://issues.folio.org/browse/MODINVSTOR-406: Make the HRID sequences consistent
* Add alter holdings/instance/item HRID sequences script.
* Expand HRID to be 11-digits instead of 8-digits.
* Add unit test to verify that current value of the sequence has not been changed.
* Modify existing unit tests.
**Open question**: Do we need to migrate existing issued HRIDs to be 11-digits?
=> MODINVSTOR-410 increase number of digits for HRID

src/main/resources/templates/db_scripts/populateEffectiveLocationForeignKey.sql, src/main/resources/templates/db_scripts/schema.json
RMB creates the UUID column `effectiveLocationId` with NULL as inital value
for all existing item records.
This is wrong.
This upgrade script populates the UUID column with the value from the jsonb column.
=> MODINVSTOR-409: effectiveLocationId foreign key upgrade script

pom.xml
This contains these fixes:
RMB 29.1.4:
* [RMB-539](https://issues.folio.org/browse/RMB-539) Fails to create index (problem with left function and operands)
* [RMB-540](https://issues.folio.org/browse/RMB-540) Unique index must not truncate for 2712 max index byte size
RMB 29.1.3:
* [RMB-536](https://issues.folio.org/browse/RMB-536) Missing f\_unaccent for compound fields full text index
* [RMB-537](https://issues.folio.org/browse/RMB-537) f\_unaccent single quote fullText tsquery sql injection
* [RMB-533](https://issues.folio.org/browse/RMB-533)/[RMB-536](https://issues.folio.org/browse/RMB-536) Another bugfix for index wrapping
* [RMB-498](https://issues.folio.org/browse/RMB-498) Truncate b-tree string for 2712 index row size
RMB 29.1.2:
* …
=> MODINVSTOR-418: Update RAML Module Builder (RMB) to 29.1.4

pom.xml
Downgrade to 29.1.0 from 29.1.4 due to performance regressions.
Reverts folio-org/mod-inventory-storage#383
=> MODINVSTOR-418 Downgrade RAML Module Builder to 29.1.0

pom.xml
This contains these fixes:
RMB 29.1.5:
* [RMB-541](https://issues.folio.org/browse/RMB-541) PgUtil.getWithOptimizedSql with left(..., 600)
RMB 29.1.4:
* [RMB-539](https://issues.folio.org/browse/RMB-539) Fails to create index (problem with left function and operands)
* [RMB-540](https://issues.folio.org/browse/RMB-540) Unique index must not truncate for 2712 max index byte size
RMB 29.1.3:
* [RMB-536](https://issues.folio.org/browse/RMB-536) Missing f\_unaccent for compound fields full text index
* [RMB-537](https://issues.folio.org/browse/RMB-537) f\_unaccent single quote fullText tsquery sql injection
* [RMB-533](https://issues.folio.org/browse/RMB-533)/[RMB-536](https://issues.folio.org/browse/RMB-536) Another bugfix for index wrapping
* …
=> MODINVSTOR-418: Update RAML Module Builder (RMB) to 29.1.5

descriptors/ModuleDescriptor-template.json, ramls/item-storage.raml, ramls/item.json, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java, src/main/resources/templates/db_scripts/populateEffectiveCallNumberComponentsForExistingItems.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberDataUpgradeTest.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/api/testdata/ItemEffectiveCallNumberComponentsTestData.java, src/test/java/org/folio/rest/api/testdata/ItemEffectiveLocationTestDataProvider.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java, src/test/java/org/folio/rest/support/builders/ItemRequestBuilder.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-361: Store effective call number type on item record
* Store effective call number type id on item record.
* Update migration script.
* Update API version.
* Refactor existing item call number related test cases and create parametrized tests instead.
=> MODINVSTOR-361: Populate effective call number type id on item.

pom.xml
Update RAML Module Builder (RMB) from 29.2.1 to 29.2.2 to get this fix:
[RMB-550](https://issues.folio.org/browse/RMB-550) Index recreation on module upgrade.
All indexes will be recreated on module upgrade, this may take long. This is needed for
[RMB-498](https://issues.folio.org/browse/RMB-498) and other index changes linked in
[MODINVSTOR-424](https://issues.folio.org/browse/MODINVSTOR-424) when an existing installation is upgraded.
=> RMB 29.2.2: Upgrade indexes on module upgrade

NEWS.md, pom.xml
Update RAML Module Builder (RMB) from 29.2.1 to 29.2.2 to get this fix:
[MODINVSTOR-430](https://issues.folio.org/browse/MODINVSTOR-430)
[RMB-550](https://issues.folio.org/browse/RMB-550) Index recreation on module upgrade.
All indexes will be recreated on module upgrade, this may take long. This is needed for
[RMB-498](https://issues.folio.org/browse/RMB-498) and other index changes linked in
[MODINVSTOR-424](https://issues.folio.org/browse/MODINVSTOR-424) when an existing installation is upgraded.
=> Release 18.2.3

descriptors/ModuleDescriptor-template.json, ramls/item-storage.raml, ramls/item-sync.raml, ramls/item.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-433: Backend: Claim returned: mark an item claim returned.
* Add `Claimed returned` to allowed item statuses list.
* Update `item-storage` and `item-sync` API versions.
=> MODINVSTOR-433: Add 'Claimed returned' to allowed item statuses list.

src/main/resources/templates/db_scripts/schema.json
Accents are not removed because they are relevant for libraries that use them.
=> MODINVSTOR-435: Add indexes for callNumber and accessionNumber.

src/main/resources/templates/db_scripts/migratePrecedingSucceedingTitles.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/PrecedingSucceedingTitleMigrationScriptTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-447
Purpose:
In order to persist connected and unconnected preceding / succeeding titles in one place, the existed connected preceding / succeeding titles need to be migrated from instance_relationships to preceding_succeeding_titles table
=> MODINVSTOR-447 Migrate connected preceding / succeeding titles from instance relationships to the new model

descriptors/ModuleDescriptor-template.json, ramls/instance-storage-batch.raml, ramls/instance-storage.raml, ramls/instance-sync.raml, ramls/instance.json, src/main/resources/templates/db_scripts/populateDiscoverySuppressIfNotSet.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceDiscoverySuppressMigrationScriptTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/MigrationTestBase.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-449: Create migration script to ensure that suppress from discovery is always yes or no.
* Set default value to `false` for `instance.discoverySuppress` property;
* Update API versions for `instance-storage/batch/sync`;
* Add migration script to set `discoverySuppress=false` if value for property is not set;
=> MODINVSTOR-449: Set default value for instance.discoverySuppress=false

reference-data/instance-relationship-types/preceding-succeeding.json, sample-data/import.sh, sample-data/instance-relationships/american-bar-association-preceding-title.json, sample-data/preceding-succeeding-titles/american-bar-association-connected-preceding-title.json, sample-data/preceding-succeeding-titles/american-bar-association-unconnected-preceding-title.json, src/main/resources/templates/db_scripts/removeOldPrecedingSucceedingTitles.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/PrecedingSucceedingTitleMigrationScriptTest.java, src/test/java/org/folio/rest/api/ReferenceTablesTest.java, src/test/java/org/folio/rest/api/SampleDataTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-451
**Purpose:** 
Remove old data after the whole Preceding/Succeeding titles migration:
**Approach:**
Remove preceding/succeeding data from:
- reference and sample data
- instance_relationship and instance_relationship_type tables
=> MODINVSTOR-451 Remove old data after the whole Preceding/Succeeding titles migration

src/main/java/org/folio/rest/exceptions/NotFoundException.java, src/main/java/org/folio/rest/exceptions/ValidationException.java, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/support/EndpointFailureHandler.java, src/main/java/org/folio/services/ItemEffectiveCallNumberComponentsService.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/http/ResourceClient.java, src/test/java/org/folio/rest/support/matchers/ItemMatchers.java
https://issues.folio.org/browse/MODINVSTOR-458 - EffecticeCallNumberComponents is not set for items in "/item-storage/batch/synchronous" API.
* Add logic to calculate effective call number components for batch item create.
* Move effective call number logic to separate service class.
=> MODINVSTOR-458: Calculate effective call number components for item batch create

pom.xml
This works for upgrading from mod-inventory-storage versions that
contain RMB >= v29.3.2 (Fameflower onwards upgrade path).
=> MODINVSTOR-460: smart index recreation on module upgrade, RMB v29.3.2

src/main/resources/templates/db_scripts/populateRmbInternalIndex.sql
18.0.0-18.2.0 require more index recreations than 18.2.1-18.2.3 because of
left(..., 600) index truncation. Therefore don't suppress index recreation
for versions before 18.2.1.
=> MODINVSTOR-459: Smart index recreation for 18.2.1-18.2.3 only

ramls/holdingsrecord.json
This also reverts commit f36857657196144a4fa77d341cf6dcabffeaaa25
"Speculatively add an `id` to the `illPolicy` virtual field"
=> MODINVSTOR-471: Duplicate class name IllPolicy, use javaType

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/MigrationTestBase.java, src/test/java/org/folio/rest/api/UpdateItemStatusDateFunctionMigrationTest.java, src/test/java/org/folio/rest/api/UpdateItemStatusDateMigrationTest.java
https://issues.folio.org/browse/MODINVSTOR-470 - Function not being migrated between Edelweiss and Fameflower.
Update `updateItemStatusDate.sql` migration version to `19.2.0`.
=> MODINVSTOR-470: Update updateItemStatusDate.sql migration version.

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/MigrationTestBase.java, src/test/java/org/folio/rest/api/UpdateItemStatusDateFunctionMigrationTest.java, src/test/java/org/folio/rest/api/UpdateItemStatusDateMigrationTest.java
https://issues.folio.org/browse/MODINVSTOR-470.
`fromModuleVersion` - has been changed to 19.1.2. Test cases have been adjusted.
=> MODINVSTOR-470: [RELEASE] Function not being migrated between Edelweiss and Fameflower

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java, src/test/java/org/folio/rest/support/builders/JsonRequestBuilder.java
https://issues.folio.org/browse/MODINVSTOR-473 - Add b-tree indexes for staffSuppress and discoverySuppress properties.
* Add index for `instance.staffSuppress` and `instance.discoverySuppress` properties;
* Add index for `item.discoverySuppress` property;
* Add index for `holdingsRecord.discoverySuppress` property;
=> MODINVSTOR-473: Add indexes for *suppress properties

src/main/resources/templates/db_scripts/audit-delete-trigger.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/AuditDeleteTest.java
Save deleted instances, holdings and items in separate tables.
Use "withAuditing" in schema.json. This instructs RMB to create separate tables that will be populated by triggers when instances, holdings and items are deleted.
Whole records are stored in audit tables.
=> MODINVSTOR-477: Store deleted instances, holdings, items in separate tables

src/main/resources/templates/db_scripts/hridSettings.sql
See https://issues.folio.org/browse/FOLIO-2447 : "Remove gen_random_uuid(), it fails in pgpool replication"
=> MODINVSTOR-483: Remove gen_random_uuid(), it fails in pgpool replication

pom.xml, src/test/java/org/folio/rest/api/InstanceStorageTest.java
https://issues.folio.org/browse/RMB-591 made these changes (https://github.com/folio-org/raml-module-builder/pull/634, https://github.com/folio-org/raml-module-builder/pull/637):
* Always return some estimated totalRecords value for optimized get sql: PgUtil.getWithOptimizedSql.
* No longer use SQL FUNCTION count_estimate_default. It may take long for full text queries when running `SELECT COUNT(*) ... LIMIT 1000`. Instead take the estimation of Postgres' EXPLAIN. Only if that estimation is < 4000 run `SELECT COUNT(*) ... LIMIT 1000`.
* If it is the last page (because > 0 but less than LIMIT records returned) we know for sure the accurate result count and return it as totalRecords.
This pull request uses RMB 29.5.0-SNAPSHOT in mod-inventory-storage master to test it in the folio-perf …
=> MODINVSTOR-468: RMB upgrade for hitcount (totalRecords) RMB-591

descriptors/ModuleDescriptor-template.json
https://issues.folio.org/browse/MODINVSTOR-482 - Securing APIs by default
* Explicitly specified that json schemas api has not required permissions
=> MODINVSTOR-482 - Securing APIs by default

descriptors/ModuleDescriptor-template.json, ramls/item-storage.raml, ramls/item-sync.raml, ramls/item.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-494 - Add 'Lost and paid' status to allowed item statuses list.
* Add the new `Lost and paid` status to item's allowed statuses;
* Update API version for `item-storage` and `item-sync`.
* Fix some static code analyzer issues in test class.
=> MODINVSTOR-494: Add 'Lost and paid' status to allowed item statuses list

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
Resolves [MODINVSTOR-479](https://issues.folio.org/browse/MODINVSTOR-479) by adding and index rule to the schema.json.
=> Modinvstor 479: Index - Filter Instance records by Date updated

descriptors/ModuleDescriptor-template.json, ramls/holdings-sync.raml, ramls/instance-sync.raml, ramls/item-sync.raml, src/main/java/org/folio/rest/impl/HoldingsBatchSyncAPI.java, src/main/java/org/folio/rest/impl/InstanceBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/StorageHelper.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
Extend each of these 3 existing HTTP POST endpoints
* /instance-storage/batch/synchronous
* /holdings-storage/batch/synchronous
* /item-storage/batch/synchronous
by an optional upsert parameter (default: false).
On upsert=true use PostgresClient.upsertBatch.
=> MODINVSTOR-478: Implement batch upsert for instances, holdings and items

src/main/java/org/folio/rest/exceptions/ValidationException.java, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/support/EndpointFailureHandler.java, src/main/java/org/folio/services/ItemEffectiveCallNumberComponentsService.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/http/ResourceClient.java, src/test/java/org/folio/rest/support/matchers/ItemMatchers.java
This is a porting of pull request #416 to version 19.1 in readiness for a 19.1.3 release.
The cherry-picking has included some additional changes not present in the changes made in that pull request. 
I imagine they were made during previous changes to mod-inventory-storage in the same files. These include (but might not be limited to) the addition of the `cannotCreateItemWithNonExistentHoldingsRecordId` test.
@bohdan-suprun could you check if these are also ok to back port?
=> Port calculating effective call number components for item batch create to 19.1 MODINVSTOR-458

ramls/holdings-sync.raml, ramls/instance-sync.raml, ramls/item-sync.raml
Add "required: false" to the upsert parameter in the raml file.
This does not affect the validation. We have unit tests without
upsert parameter that succeed for all 3 API endpoints.
It affects the documentation published at
https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/instance-sync.html#instance_storage_batch_synchronous_post
https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/holdings-sync.html#holdings_storage_batch_synchronous_post
https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/item-sync.html#item_storage_batch_synchronous_post
where upsert parameter incorrectly is marked as "required" in red.
=> MODINVSTOR-478: Declare upsert parameter as optional

pom.xml
RMB [v30.0.2](https://github.com/folio-org/raml-module-builder/releases/tag/v30.0.2) contains the fix
* [RMB-637](https://issues.folio.org/browse/RMB-637) Run ANALYZE after index (re-)creation
that is needed to solve [FOLIO-2625](https://issues.folio.org/browse/FOLIO-2625).
=> FOLIO-2625: Upgrade to RMB v30.0.2 for hitcount/analyze fix

pom.xml
Upgrade RMB from 30.0.2 to 30.0.3.
No longer downgrade vertx-unit from 3.9.1 to 3.9.0.
The RMB upgrade contains two fixes relevant for mod-inventory-storage:
* [RMB-645](https://issues.folio.org/browse/RMB-645) Use where-only clause for the "count query" for consistent hit count estimations
* [RMB-640](https://issues.folio.org/browse/RMB-640) Fix Sorby title and limit=0 gives zero hits
=> MODINVSTOR-519: Upgrade RMB to 30.0.3, fixing inconsistent hit counts

NEWS.md, pom.xml
* Upgrade to RAML Module Builder 30.0.3 (MODINVSTOR-519):
* Use where-only clause for the "count query" for consistent hit count estimations (RMB-645)
* Fix sorby title and limit=0 gives zero hits (RMB-640)
=> Release 19.2.1

src/main/resources/templates/db_scripts/migrateItemCopyNumberToSingleValue.sql, src/main/resources/templates/db_scripts/populateDiscoverySuppressIfNotSet.sql, src/main/resources/templates/db_scripts/populateEffectiveCallNumberComponentsForExistingItems.sql, src/main/resources/templates/db_scripts/populateEffectiveLocationForExistingItems.sql, src/main/resources/templates/db_scripts/populateEffectiveLocationForeignKey.sql
Replace `UPDATE pg_trigger` (that requires special permissions) by
`ALTER TABLE <table> DISABLE TRIGGER USER` and
`ALTER TABLE <table> ENABLE TRIGGER USER`.
`USER` excludes internally generated constraint triggers such as those that
are used to implement foreign key constraints or deferrable uniqueness and
exclusion constraints that require superuser privileges.
=> MODINVSTOR-476: Avoid special permissions for trigger disabling/enabling

pom.xml, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
First try out RMB v30.2.0 in master to see whether there are any regressions in folio-testing and folio-perf.
See https://issues.folio.org/browse/RMB-652 '"may not be null" changed to "must not be null" (hibernate-validator)'
why several unit tests were changed to also accept the new wording.
=> MODINVSTOR-522: Upgrade RMB to v30.2.0

descriptors/ModuleDescriptor-template.json
Added the ‘inventory-storage.oai-pmh-view.instances.collection.get’ permission to collection of ’inventory-storage.all’ acquired to setup in anew environment : https://issues.folio.org/browse/MODINVSTOR-524.
=> MODINVSTOR-524: Change permissions location for oai-pmh view

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
The JSON array characters ["", ""] are ignored by full text search,
no need to strip them.
The generated query for subjects=a* uses the new index instance_subjects_idx_ft:
```
postgres=# explain analyze select count(*) from instance WHERE to_tsvector('simple', f_unaccent(instance.jsonb->>'subjects')) @@ tsquery_phrase(f_unaccent('a*'));
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------
Aggregate  (cost=35.68..35.69 rows=1 width=8) (actual time=0.029..0.029 rows=1 loops=1)
->  Bitmap Heap Scan on instance  (cost=20.08..35.66 rows=10 width=0) (actual time=0.022..0.027 rows=5 loops=1)
Recheck Cond: (to_tsvector('simple'::regconfig, f_unaccent((jsonb ->> 'subjects'::text))) @@ …
```
=> MODINVSTOR-499: Add Index for Instances Full-text Subjects Search

pom.xml
Most notable fix: RMB-657 Database connections no longer
get cancelled when they take longer than 60 seconds.
This probably resolves MODINVSTOR-527.
Changelog:
https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.2
=> MODINVSTOR-528: Upgrade to RMB 30.2.2

pom.xml
There is no need for mod-inventory-storage to get this RMB v30.2.3
release but I would like to have it in the performance test and in
folio-testing and folio-snapshot to be sure that there are no regressions.
=> MODINVSTOR-531: Update to RMB v30.2.3

pom.xml
Updating RMB from 30.2.3 to 30.2.4 fixes this:
https://issues.folio.org/browse/RMB-673 totalRecords returns exact hit count for limit=0
https://issues.folio.org/browse/RMB-670 Fix RestVerticle requestId logging, replace log4j 1.2 MDC by log4j 2 ThreadContext
=> MODINVSTOR-532: RMB 30.2.4: totalRecords for limit=0, requestId logging

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/LocationsTest.java, src/test/java/org/folio/rest/api/ServicePointTest.java
https://issues.folio.org/browse/MODINVSTOR-472 - Search queries without database index
* Add b-tree indexes:
* `location.primaryServicePoint`
* `service_point.pickupLocation`
* `item.purchaseOrderLineIdentifier`
=> MODINVSTOR-472: Add missing indexes.

src/main/resources/templates/db_scripts/migratePrecedingSucceedingTitles.sql
GBV tried migrating from mod-inventory-storage-18.2.3 to mod-inventory-storage-19.2.4 three times.
The second time failed with this error:
```
INFO  PostgresClient [30313837eqId] trying to execute:  INSERT INTO diku_mod_inventory_storage.preceding_succeeding_title (id, jsonb)   SELECT id, jsonb_build_object(     'id', jsonb->'id',     'metadata', jsonb->'metadata',    'precedingInstanceId', jsonb->'superInstanceId',     'succeedingInstanceId', jsonb->'subInstanceId')   FROM diku_mod_inventory_storage.instance_relationship as ir   WHERE ir.instanceRelationshipTypeId ='cde80cc2-0c8b-4672-82d4-721e51dcb990'
ERROR PostgresClient [30313841eqId] FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »preceding_succeeding_title_pkey«
Detail: Schlüssel …
```
=> MODINVSTOR-541: Make migratePrecedingSucceedingTitles.sql idempotent

descriptors/ModuleDescriptor-template.json, ramls/item-storage.raml, ramls/item-sync.raml, ramls/item.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-503 - Add 'Aged to lost' status to allowed item statuses list
* Add `Aged to lost` item status;
* Update `item-storage` API version;
* Update `item-batch-sync` API version;
=> MODINVSTOR-503: Add new 'Aged to lost' item status.

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/item-storage.raml, ramls/item-sync.raml, ramls/item.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
Release 19.3.0 includes these features:
* Add 'Aged to lost' status to allowed item statuses list (MODINVSTOR-503)
* Solving issue with GBV by making migration for preceeding and succeeding titles to be possible to run several times without failing (MODINVSTOR-541)
* Separate filtering from response generation in oai-pmh view (MODINVSTOR-536)
* Item record. Effective call number (item), eye readable. Search on exact data in Call number data element (MODINVSTOR-481)
* Holdings record. Call number, eye readable. Search on exact data in Call number data element (MODINVSTOR-480)
* Search queries without database index (MODINVSTOR-472)
* Upgrade to raml-module-builder (RMB) 30.2.4 (MODINVSTOR-532)
* Expand oai-pmh view with additional fields (MODINVSTOR-498)
* OAI-PMH view doesn't respond in …
=> MODINVSTOR-539 Release mod-inventory-storage 19.3.0

src/main/resources/templates/db_scripts/oaipmh/createOaiPmhViewFunction.sql, src/main/resources/templates/db_scripts/schema.json
This change fixes version of SQL schema for "oai pmh view" fucntionality and added dropping of legacy functions before their creation for the mainline.
=> Ported fixes of release 19.3.0 issue for mainline.

NEWS.md, pom.xml
* Fixed version of sql schema for oai pmh view. Updated sql script with droping exisitng function due to output data's column renaming.
MODINVSTOR-547: Upgrading mod-inventory-storage to 19.3.0 results in error log output indicating update failed
https://issues.folio.org/browse/MODINVSTOR-547
=> Release mod-inventory-storage 19.3.1 (MODINVSTOR-549)

Dockerfile, Jenkinsfile, docker/docker-entrypoint.sh, pom.xml
This reverts commit 71c619a6fbb35ab1b0bfa1b8a56d6d974e469f94.
This fixes https://issues.folio.org/browse/MODINVSTOR-558
'/item-storage/items fails because "module name: netty_parent"'
=> MODINVSTOR-558: Revert "Update to OpenJDK-11 MOVINVSTOR-555 (#485)"

src/main/java/org/folio/rest/support/RowStreamToBufferAdapter.java
Fixing this omission is needed for the next RMB update:
https://issues.folio.org/browse/RMB-693
see upgrading.md in https://github.com/folio-org/raml-module-builder/pull/741/files
If the RowStream is not closed, the prepared statement names remains open on the PostgreSQL connection preventing the number of prepared statements to exceed 0x10000. This results in `ERROR: prepared statement "XYZ" already exists`
=> MODINVSTOR-556: RowStreamToBufferAdapter should close RowStream<Row>

pom.xml
Most notable bug fixes in [RMB 30.2.5](https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.5):
https://issues.folio.org/browse/RMB-693 "Close prepared statements
in PostgresClient stream get"
This fixes https://issues.folio.org/browse/MODINVSTOR-540 "ERROR:
prepared statement XYZ already exists"
https://issues.folio.org/browse/RMB-684 "GET query returns no
records when offset value >= estimated totalRecords"
=> MODINVSTOR-557: Upgrade to RMB 30.2.5

pom.xml
https://github.com/folio-org/raml-module-builder/releases/tag/v30.2.6 :
* [RMB-701](https://issues.folio.org/browse/RMB-701) Update to [Vert.x 3.9.2](https://github.com/vert-x3/wiki/wiki/3.9.2-Release-Notes), fixing WebClient request timeout races
* [RMB-700](https://issues.folio.org/browse/RMB-700) NPE when RestVerticle calls LogUtil.formatStatsLogMessage
* [RMB-677](https://issues.folio.org/browse/RMB-677) Close PostgreSQL connection after invalid CQL failure
=> MODINVSTOR-562: Upgrade to RMB 30.2.6

NEWS.md, pom.xml
This updates RMB to v30.2.7 fixing [RMB-703](https://issues.folio.org/browse/RMB-703) "Full text search doesn't match URLs containing &" needed for [MODDICORE-80](https://issues.folio.org/browse/MODDICORE-80) "Cannot match on eAccess URI field"
=> MODINVSTOR-568: Release 19.3.3

pom.xml, src/main/java/org/folio/rest/impl/InstanceStorageBatchAPI.java
This is temporarily needed to verify this Goldenrod hot-fix:
MODINVSTOR-568 Release mod-inventory-storage 19.3.3
MODINVSTOR-567 Upgrade b19.3 (Goldenrod) to RMB 30.2.7
This updates RMB to v30.2.7 fixing RMB-703 "Full text search
doesn't match URLs containing &" needed for
MODDICORE-80 "Cannot match on eAccess URI field"
This pull request
* excludes Log4j2Plugins.dat from the shaded jar, otherwise
the logging will fail with "Unrecognized format specifier"
* replaces populateMetaDataForList by RMB's MetadataUtil.populateMetadata
because RMB has removed JwtUtils.
=> MODINVSTOR-569: Upgrade RMB to 31.1.0-SNAPSHOT on master

descriptors/ModuleDescriptor-template.json, ramls/instance-storage.raml
https://issues.folio.org/browse/MODINVSTOR-535 - Incorrect required permissions for instance relationship endpoints
=> MODINVSTOR-535: Fix instance-relationships API permissions.

ramls/examples/inventory-items-and-holdings.json, ramls/holdingsrecord.json, ramls/inventory-hierarchy/inventory-instance-records.json, ramls/item.json, ramls/location.json, src/main/resources/templates/db_scripts/inventory-hierarchy/createRecordsViewFunction.sql
Fixed error with handling "onlyInstanceUpdateDate" flag passed to "updated instance ids" routine;
Fixed returning holdings where there are no items at all.
Removed empty objects from data when there are no items in holdings records.
Fixed copy-past issue which is affecting returned holdings data when there are no items.
Jira: https://issues.folio.org/browse/MODINVSTOR-570
=> Fixed format of returning empty data for "items" and "holdings" fields;

src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/LocationUnitTest.java, src/test/java/org/folio/rest/api/LocationsTest.java, src/test/java/org/folio/rest/api/MigrationTestBase.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/client/LoanTypesClient.java, src/test/java/org/folio/rest/support/client/MaterialTypesClient.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
In addition three catch blocks are fixed to no longer swallow
stack traces but pass on the (possibly checked) exception wrapped
in a RuntimeException.
=> MODINVSTOR-575 Increase request timeout from 5 s to 10 s in unit tests

src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
The index contains all the dateOfPublication
values of the publication array. Example array:
```
"publication" : [ {
"publisher" : "Random House",
"place" : "New York",
"dateOfPublication" : "[1998]",
"role" : "Publication"
}, {
"publisher" : null,
"place" : null,
"dateOfPublication" : "©1998",
"role" : null
}
]
```
=> MODINVSTOR-578: Add `dateOfPublication` index

descriptors/ModuleDescriptor-template.json, ramls/instance.json, ramls/item.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
- add matchKey property to Instance
- add enumeration element "Unknown" for Item.status
This pull request suggests two changes to Inventory Storage in order to use Inventory for shared indexes, with 1)  being the most important: 
1)
It's suggested to extend the Instance schema of Inventory storage with a unique, optional property `matchKey`. 
`Instance.matchKey` can be used in a setting where multiple libraries contribute bibliographic records to the same Inventory -- a shared index --  and thus need a way to identify identical instances across multiple catalogs in order to provide updates to bibliographic data or holdings in the shared index. One option is to use match key values based on metadata in the bibliographic record for example.  
Please note that the change includes a new index …
=> Add support for using inventory as shared index

src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/test/java/org/folio/rest/api/ReferenceTablesTest.java
https://issues.folio.org/browse/MODINVSTOR-590 - Setting > Inventory > Holdings > Holdings source, predefined values (FOLIO, MARC)
=> MODINVSTOR-590: Load holdings-sources reference data during tenant init.

.gitignore, descriptors/ModuleDescriptor-template.json, ramls/instance.json, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
matchKey can be used for storing a key like the Gold Rush® match key
that identifies "same" bibliographic records from separate
library catalogs. It basically implements a compare of metadata
in the bibliographic records.
This way, one Inventory Instance can represent multiple underlying
bibliographic records.
matchKey could conceivably hold other matching schemes instead if
desired.
=> MODINVSTOR-587: Add property `Instance.matchKey` for building a shared index with Inventory

NEWS.md, pom.xml
https://issues.folio.org/browse/MODINVSTOR-591.
Includes upgrade to RMB 30.2.8 / Vert.x 3.9.3 which resolves [RMB-732](https://issues.folio.org/browse/RMB-732)
=> MODINVSTOR-591 - Release 19.3.4

pom.xml, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/StatisticalCodeTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/support/builders/StatisticalCodeBuilder.java, src/test/java/org/folio/rest/support/fixtures/StatisticalCodeFixture.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-596 - Settings > Inventory > Statistical codes. Statistical code name is being case sensitive.
* Add UK for statistical_code.name.
* Add lombok dependency.
* Add StatisticalCodeBuilder/Fixture classes.
=> MODINVSTOR-596: Add unique key constraint for statistical_code.name.

pom.xml
RMB master=31.2.0-SNAPSHOT contains a fix for the
"prepared statement "XYZ" already exists" issue ([MODINVSTOR-540](https://issues.folio.org/browse/MODINVSTOR-602)).
Merging this to mod-inventory-storage master deploys it to
the FOLIO reference environments for review.
=> MODINVSTOR-602: Upgrade to RMB 31.2.0-SNAPSHOT and Vert.x 3.8.4

pom.xml
RMB 31.1.3 contains:
* [RMB-737](https://issues.folio.org/browse/RMB-737) Update to Junit and jupiter to 4.13.1
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fixed bug: RowStream fetch
can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778
=> MODINVSTOR-604: Upgrade to RMB 31.1.3

NEWS.md, pom.xml
This has been tested on master, see https://issues.folio.org/browse/MODINVSTOR-602
RMB 30.2.9 contains this:
* [RMB-740](https://issues.folio.org/browse/RMB-740) Use FOLIO fork of vertx-sql-client and vertx-pg-client with
the following two patches
* [RMB-739](https://issues.folio.org/browse/RMB-739) Make RMB's DB\_CONNECTIONRELEASEDELAY work again, defaults to 60 seconds
* [FOLIO-2840](https://issues.folio.org/browse/FOLIO-2840) Fix duplicate names causing 'prepared statement "XYZ" already exists'
* [RMB-738](https://issues.folio.org/browse/RMB-738) Upgrade to Vert.x 3.9.4, most notable fixed bug: RowStream fetch can close prematurely the stream https://github.com/eclipse-vertx/vertx-sql-client/issues/778
=> MODINVSTOR-605: Upgrade to RMB v30.2.9 and Vert.x 3.9.4, and release 19.3.5

pom.xml
RMB 31.1.5 provides
* RMB-750 Change lock for "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
RMB 31.1.4 provides
* RMB-744 fix "tuple concurrently updated" when upgrading Q2 to Q3 (REVOKE)
=> MODINVSTOR-611: Upgrade to RMB 31.1.5

NEWS.md, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
For individual items, I initially addressed this by setting the 
status date from the item creation date.  However, this does not work with
batch-created items, for reasons I still have not been able to puzzle out.
Setting batch-created item records to use the item creation date causes all
batch-item creation operations to fail with a status of "Bad request" (400).
So, I changed both creation methods to use the current local date/time as the 
initial status updated date.  I thought it was better to have them both behave 
consistently.  This means the status update date will not exactly match the item 
creation date, but the notes on the bug report indicate this is expected behavior.
I adjusted all tests that expected the status modification date to be null 
and also added a test that …
=> MODINVSTOR-508: Item status date is missing on creation

NEWS.md, src/main/java/org/folio/rest/impl/InstanceBatchSyncAPI.java, src/main/java/org/folio/rest/impl/InstanceStorageAPI.java, src/main/java/org/folio/rest/impl/InstanceStorageBatchAPI.java, src/main/java/org/folio/rest/support/StatusUpdatedDateGenerator.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
In line with MODINVSTOR-508, I changed operations here to use the current 
date/time as the initial status updated date.  I felt again that it was 
important that creation operations behave consistently.
Getting the current date and time and inserting it into the instance creation
process was the easy part.  What took more time was rewriting tests that 
either expected a null value, or were not checking the status update field
for any value at all.  It also took a while for me to realize there were two 
separate endpoints that batch-create instances.  For single instance and regular
batch-creation processes, I built checking for the status update date into existing 
tests where it seemed to make sense, usually into the initial check to see if such 
items could be correctly created.  For …
=> MODINVSTOR-509: Instance. New Instance. Instance status date is missing

src/test/java/org/folio/rest/api/InstanceRelationshipsTest.java, src/test/java/org/folio/rest/api/InventoryHierarchyViewTest.java, src/test/java/org/folio/rest/api/OaiPmhViewTest.java, src/test/java/org/folio/rest/api/PrecedingSucceedingTitleTest.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java
Whilst reviewing pull requests, it became apparent that some tests (e.g. any in `ItemStorageTests` couldn't be executed individually, due to the tests not creating the default instance type.
=> Create instance type before tests MODINVSTOR-613

pom.xml, src/main/java/org/folio/rest/impl/AbstractInstanceRecordsAPI.java, src/test/java/org/folio/rest/api/AbstractInstanceRecordsAPITest.java
https://issues.folio.org/browse/MODINVSTOR-614 - inventory-storage crashes after grabbing all available DB connections.
Seems we don't need to call async handler when we're updating the response directly. RMB does not call the async jhandler as well for streaming see  https://github.com/folio-org/raml-module-builder/blob/master/domain-models-runtime/src/main/java/org/folio/rest/persist/PgUtil.java#L556, there is no asynHandler param being passed.
=> MODINVSTOR-614: Do not call asyncHandler when response is being updated directly.

ramls/item.json
This is for mod-graphql's benefit, and is needed for ZF-26.
=> Add virtual link-field "materialType" to item schema

src/main/java/org/folio/rest/impl/HoldingsBatchSyncAPI.java, src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java, src/main/java/org/folio/rest/impl/InstanceBatchSyncAPI.java, src/main/java/org/folio/rest/impl/InstanceStorageAPI.java, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/impl/StorageHelper.java, src/test/java/org/folio/rest/api/HridSettingsStorageTest.java
Replace StorageHelper.completeFuture(T) by Future.succeededFuture(T).
It duplicates the Vert.x method:
https://github.com/eclipse-vertx/vert.x/blob/4.0.0.CR2/src/main/java/io/vertx/core/Future.java#L59-L72
=> MODINVSTOR-630: Delete StorageHelper.completeFuture(T)

src/main/java/org/folio/rest/exceptions/BadRequestException.java, src/main/java/org/folio/rest/exceptions/InventoryProcessingException.java, src/main/java/org/folio/rest/exceptions/NotFoundException.java, src/main/java/org/folio/rest/exceptions/ValidationException.java, src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java, src/main/java/org/folio/rest/impl/InstanceStorageAPI.java, src/main/java/org/folio/rest/impl/ItemBatchSyncAPI.java, src/main/java/org/folio/rest/impl/ItemStorageAPI.java, src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java, src/main/java/org/folio/rest/support/EndpointFailureHandler.java, src/main/java/org/folio/rest/support/ItemEffectiveLocationUtil.java, src/main/java/org/folio/rest/support/ResponseUtil.java, src/main/java/org/folio/services/ItemEffectiveValuesService.java, src/main/java/org/folio/services/domainevent/BaseDomainEventService.java, src/main/java/org/folio/services/domainevent/DomainEvent.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventService.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/item/ItemService.java, src/main/java/org/folio/services/item/effectivevalues/ItemWithHolding.java, src/main/java/org/folio/services/kafka/KafkaProducerService.java, src/main/java/org/folio/services/persist/PostgresClientFuturized.java, src/test/java/org/folio/services/kafka/KafkaProducerServiceTest.java
https://issues.folio.org/browse/MODINVSTOR-647 - Refactor ItemStorageAPI and HoldingsStorageAPI before implementing domain events.
* Always retrieve holdings record for item on create or update (was if required - it is now required for domain events to set instance id)- see [ItemEffectiveValuesService](https://github.com/folio-org/mod-inventory-storage/pull/561/files#diff-e47d87f2ed99e78767a00a57c7f2f46c76b05dc951615c9fbf76e7b374241d82)
* Use chaining for item storage create/update/delete methods to reduce amount of callbacks and move the logic to a [service](https://github.com/folio-org/mod-inventory-storage/pull/561/files#diff-78dff0242682c91208ab3b3ce644115ee6d3cb522c0697639db65927241547fe) class;
* Use chaining for holding storage update methods to reduce method complexity and move …
=> MODINVSTOR-647: Refactor ItemStorageAPI and HoldingStorageAPI#put.

src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/main/java/org/folio/services/kafka/KafkaMessage.java, src/main/java/org/folio/services/kafka/KafkaProducerService.java, src/main/java/org/folio/services/kafka/topic/KafkaTopic.java, src/test/java/org/folio/rest/support/HttpClient.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/services/kafka/KafkaProducerServiceTest.java
https://issues.folio.org/browse/MODINVSTOR-654 - Propagate okapi request headers to kafka messages.
* Introduce KafkaMessage class that holds topic, instanceId, payload and headers to send.
* Send okapi url and tenant headers for kafka message.
* Adjust FakeKafkaConsumer to use `KafkaMessage` class so that we will be able to verify headers as well as payload.
* Verify that okapi headers are received in event consumer.
=> MODINVSTOR-654: Propagate okapi headers to kafka events

pom.xml, ramls/record-bulk.raml, src/main/java/org/folio/rest/impl/RecordBulkAPI.java, src/test/java/org/folio/rest/api/RecordBulkTest.java
Moved ticket to mod-inventory-storage project https://issues.folio.org/browse/MODINVSTOR-657
Add offset&&limit query params to /instance-bulk/ids endpoint
Update RecordBulkAPI class and unit tests
If the request contains offset&&limit query params then the response will contain the incorrect value of "totalRecords" that doesn't correspond to the actual amount of records in JSON. It happens because of the wrong building count query without limit and offset in PostgresClient.buildQueryHelper method. At the same time, the same method builds select query with limit and offset.
=> MODINVSTOR-657 Add limit query param to /instance-bulk/ids endpoint

src/main/java/org/folio/persist/InstanceRepository.java, src/main/java/org/folio/rest/impl/InstanceBatchSyncAPI.java, src/main/java/org/folio/rest/impl/InstanceStorageBatchAPI.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java, src/main/java/org/folio/services/instance/InstanceService.java, src/main/resources/kafka-topics.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
https://issues.folio.org/browse/MODINVSTOR-644 - Domain events sending in inventory-storage for instance [batch APIs]
* Introduce `InstanceRepository` class;
* Send domain events on instance batch create (covers both batch-sync new API and instances/batch - deprecated API).
* Set `50` as replication factor for `inventory.instance` topic.
=> MODINVSTOR-644: Send domain events on instance batch create/upsert 

README.MD, src/main/java/org/folio/persist/HoldingsRepository.java, src/main/java/org/folio/persist/ItemRepository.java, src/main/java/org/folio/rest/impl/InstanceStorageAPI.java, src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/DomainEvent.java, src/main/java/org/folio/services/domainevent/DomainEventType.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/item/ItemService.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
https://issues.folio.org/browse/MODINVSTOR-664 - Publish single deleteAll message for items/holdings/instances.
* Publish DELETE_ALL event when all instances/items/holdings are being removed.
=> MODINVSTOR-664: Publish single delete all event when all items/holdings/instances are removed.

src/main/resources/templates/db_scripts/populateRetainLeadingZeroesSetting.sql, src/test/java/org/folio/rest/api/RetainLeadingZeroesMigrationScriptTest.java
Fix "ERROR: cannot replace existing key" during update operation in the SQL script.
Added addition check in the SQL script.
[MODINVSTOR-675](https://issues.folio.org/browse/MODINVSTOR-675)
=> Fix MODINVSTOR-675 (ERROR: cannot replace existing key).

src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java, src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
Use loadData and create the topis before any other things are loaded.
With this, we don't need to override postTenant anymore which is
discouraged.
=> Fix Kafka topics created when module is disabled MODINVSTOR-691

descriptors/ModuleDescriptor-template.json, ramls/instance-storage.raml
The instance-storage interface needs to be updated because of adding of contributorsNames index.
Please see https://issues.folio.org/browse/MODINVSTOR-707 and its related tickets.
=> Update instance-storage from 7.6 to 7.7

src/test/java/org/folio/rest/api/InstanceStorageTest.java
As requested, I added a second test for the classifications index without the subfield notation.  I rearranged shared setup code into a method so I would not have to duplicate it.
=> MODINVSTOR-716: adding second test for classifications index

descriptors/ModuleDescriptor-template.json, ramls/instance-storage.raml, ramls/instance.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
Add `publicationPeriod` properties to `instance`.
As per Magda:
>  I believe that implementation can be achieved by having two fields: year1 and year2 and from your example above it would be populated as follows:
> Record A has a publication year of 1999, no publication start year and no publication end year – year1 is populated with 1999, year2 is blank
Record B has no publication year, a publication start year of 1996 and publication end year of 2001 – year1 is 1996 and year2 is 2001
Record C has no publication year, a publication start year of 1998 and no publication end year – year1 is 1998 and year2 is blank
Record D has no publication year, no publication start year and a publication end year of 2000 – year1 is blank year2 is 2000
=> MODINVSTOR-723: Add publication year and publication period properties.

src/main/java/org/folio/persist/NotificationSendingErrorRepository.java, src/main/java/org/folio/persist/entity/NotificationSendingError.java, src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/FailureHandler.java, src/main/java/org/folio/services/domainevent/LogToDbFailureHandler.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/NotificationSendingErrorRepositoryTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/services/domainevent/CommonDomainEventPublisherTest.java, src/test/java/org/folio/services/domainevent/LogToDbFailureHandlerTest.java
* Create new `notification_sending_error` table with following structure:
* id;
* topicName;
* partitionKey;
* payload;
* error;
* incidentDateTime;
* Introduce `FailureHandler` interface that injected into domain events publisher class
* Add LogToDbTable default implementation for `FailureHandler`.
=> MODINVSTOR-663: Log failed domain events to internal table.

src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java
Fix
ItemShelvingOrderMigrationServiceApiTest#shouldStopProcessingWhenCannotConvertItem
depends on other test (can not be run in isolation - when Vert.x
4.1.0 (Beta or CR1) is in use).
=> Fix shouldStopProcessingWhenCa.. MODINVSTOR-725

pom.xml, src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java, src/test/java/org/folio/rest/api/NotificationSendingErrorRepositoryTest.java, src/test/java/org/folio/services/domainevent/CommonDomainEventPublisherTest.java, src/test/java/org/folio/services/domainevent/LogToDbFailureHandlerTest.java, src/test/java/org/folio/services/migration/BatchedReadStreamTest.java
This project already uses Hamcrest for matchers, why has an alternative been introduced?
=> MODINVSTOR-734: Replace Assertj matchers by Hamcrest matchers

NEWS.md, pom.xml
As RMB 33.x removes support for the `embed_postgres` parameter
=> Change version to 21.0.0 MODINVSTOR-725

descriptors/ModuleDescriptor-template.json
The version was changed in the NEWS and RAML during MODINVSTOR-670 however not changed in the module descriptor
=> Make provided inventory-hierarchy version consistent MODINVSTOR-735

src/main/resources/templates/db_scripts/dropLegacyItemEffectiveLocationFunctions.sql, src/main/resources/templates/db_scripts/effectiveLocationFunctionCreator.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/LegacyItemEffectiveLocationMigrationScriptTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
I wrote a script to remove the functions and put an entry to run it in the
schema file.  I didn't put this in the news file, it didn't seem significant
enough to warrant inclusion.
I had problems with some of the tests that looked at times failing 
because the test was a bit too exact. So I adjusted a few of the 
tests to have longer margins for error when comparing times.
Also found and removed a redundant library import in one of the 
test files.
=> MODINVSTOR-722: Remove update effective location database functions

NEWS.md, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
I made the modifications to the index outlined in the jira issue.
I then wrote a test for the new search behavior.
I believe this is supposed to be backported, so I added
The change under the last release in the NEWS file.
Once this is approved, I'll hotfix and backport.
=> MODINVSTOR-719: Add indexTitle, alternativeTitles, series to keyword search index

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, src/main/java/org/folio/Environment.java, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/ItemDomainEventPublisher.java, src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java, src/main/java/org/folio/services/kafka/topic/KafkaTopic.java, src/main/java/org/folio/services/reindex/ReindexJobRunner.java, src/test/java/org/folio/rest/api/ItemDamagedStatusAPITest.java, src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/services/domainevent/CommonDomainEventPublisherTest.java, src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
Publish all inventory messages to different topics, whose name starts with the environment, then the tenant ID e.g. `test.foo_tenant.inventory.instance`
None of the existing topics have been removed, as I wasn't sure about the requirements or the impact on pre-existing consumers.
This change is **implementation compatibility breaking** and needs to be deployed together with changes to consuming modules.
Usually, I prefer to refactor the code to make the change easier before making a change. Given the urgency of this change, the need to back port it and my lack of familiarity with the code, I chose to try to make the least amount of changes.
There are changes to the tests in order to be able to change the topic names in them independently of the production code. I find this useful for …
=> Include tenant and environment in topic names MODINVSTOR-738

descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/Environment.java, src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/ItemDomainEventPublisher.java, src/main/java/org/folio/services/kafka/KafkaMessage.java, src/main/java/org/folio/services/kafka/KafkaProducerService.java, src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java, src/main/java/org/folio/services/kafka/topic/KafkaTopic.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/services/kafka/KafkaProducerServiceTest.java, src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
Publish all inventory messages to different topics, whose name starts with the environment, then the tenant ID e.g. `test.foo_tenant.inventory.instance`
None of the existing topics have been removed, as I wasn't sure about the requirements or the impact on pre-existing consumers.
This change is **implementation compatibility breaking** and needs to be deployed together with changes to consuming modules.
Usually, I prefer to refactor the code to make the change easier before making a change. Given the urgency of this change, that it is being made to an existing release and my lack of familiarity with the code, I chose to try to make the least amount of changes.
There are changes to the tests in order to be able to change the topic names in them independently of the production code. I find …
=> Use environment and tenant in topic names MODINVSTOR-744

CODEOWNERS
As the module is maintained by multiple teams the review requests generated by the code owners definition leads to unnecessary notifications that slow down the review process as folks start to ignore them
=> Remove code owners MODINVSTOR-775

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/ItemStorageTest.java
To be sure that the unique item barcode index of release v21.0.4 gets deleted this DELETE entry in schema.json is kept (it has been released in mod-inventory-storage-21.0.5):
```
"uniqueIndex": [
{
"fieldName": "barcode",
"tOps": "DELETE",
"caseSensitive": false,
"removeAccents": false
},
```
This is a workaround for this issue in RMB < v33.0.3: [RMB-864](https://issues.folio.org/browse/RMB-864) Ignore deleted index in schema.json.
=> MODINVSTOR-783: Revert item barcode indexes, release v21.0.6

src/main/resources/templates/db_scripts/populatePublicationPeriod.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/PublicationPeriodMigrationTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
To speed up the migration use SQL (not Java) to parse
the publication array and populate the publicationPeriod field.
=> MODINVSTOR-774: populatePublicationPeriod.sql

NEWS.md, pom.xml
Fix database memory bug by updating RMB to 33.1.1 and Vert.x to 4.1.4 (MODINVSTOR-793, MODINVSTOR-795)
=> MODINVSTOR-795: Backport database memory fix (RMB v33.1.1,  and Vert.x to 4.1.4 (MODINVSTOR-793)

ramls/instance-storage.raml
The presence of source records in mod-inventory-storage creates ambiguity between them and source records defined in mod-source-record-storage.
This has led to folks thinking that documentation in this module about automatic source record deletion, that refers to source records, refers to source records in mod-source-record-storage rather than in this module.
It has been requested that we change the wording to remove that ambiguity. The new wording has been provided by @a-mbreaux 
(Personally, I don't think these kinds of reference to other modules were intended in an interface definition, however I'm changing it at folks request)
=> Describe how mod-source-record-storage  source records are not automatically deleted MODINVSTOR-828

NEWS.md, ramls/instance.json, sample-data/instances/bridget-jones-baby.json, src/test/java/org/folio/rest/api/InstanceStorageTest.java
Not a lot to say here-I changed the json description of the records
so that it would have this field.  I also added it to one of the sample 
records.  Then I modified existing tests to set the field to verify 
that it works.
=> MODINVSTOR-832: Adding admin notes field to instance records

ramls/instance.json
https://issues.folio.org/browse/MODINVSTOR-816
=> MODINVSTOR-816: previouslyHeld default must be boolean, not string

src/main/java/org/folio/rest/impl/TenantRefAPI.java, src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
There are a lot of unused topics that can be on envs with several tenants. To decrease pressure on consumers modules it’s nice to clean unused topics in Kafka.
Delete topics for the tenant on the tenant delete operation
=> MODINVSTOR-827 Clean kafka topics on tenant delete

src/test/java/org/folio/services/domainevent/LogToDbFailureHandlerTest.java
Loosen date check, as current date and incidental date
may be equal (on a fast system).
=> Fix test LogToDb..canHandleFailure MODINVSTOR-840

src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java
The spurious test failures indicate that the _version property
is still 1 but is expected to be 2.
=> MODINVSTOR-841: Spurious failures canCalculateEffectiveCallNumberPropertyOnUpdate

README.MD
For development and reference environments FOLIO uses PostgreSQL 12,
this is the only version that FOLIO officially supports:
https://issues.folio.org/browse/FOLIO-2145
This pull request
https://github.com/folio-org/mod-inventory-storage/pull/700/files
https://issues.folio.org/browse/MODINVSTOR-676
"Add statistical code ids exists constraint for item create/update"
uses
`CREATE TRIGGER ... EXECUTE FUNCTION` syntax that is available
from PostgreSQL 11 but not in older versions:
https://www.postgresql.org/docs/11/sql-createtrigger.html
https://www.postgresql.org/docs/10/sql-createtrigger.html
=> FOLIO supports PostgreSQL 12 only.

NEWS.md, pom.xml
Resolve CVE-2021-44228 as per [MODINVSTOR-851](https://issues.folio.org/browse/MODINVSTOR-851).
=> MODINVSTOR-851: Upgrade to RMB 33.1.3

NEWS.md, pom.xml
Resolve CVE-2021-44228 as per [MODINVSTOR-853](https://issues.folio.org/browse/MODINVSTOR-853).
=> MODINVSTOR-853: Upgrade to RMB 33.1.3 (Juniper R2 2021).

sample-data/bound-with/instances/bwinst0001.json, sample-data/bound-with/instances/bwinst0002.json, sample-data/bound-with/instances/bwinst0003.json, sample-data/bound-with/items/bwit000000001.json
On references env some tags from instances presented in ES indeed, but not in mod-tags
Remove tags from sample data that are not presented into the mod-tags
[MODINVSTOR-817](https://issues.folio.org/browse/MODINVSTOR-817)
[UI Bugfest](https://issues.folio.org/browse/UIIN-1809)
=> MODINVSTOR-817 Remove "bound-with" tag

PERSONAL_DATA_DISCLOSURE.md
Provide personal data disclosure form to comply with Folio policies and guidelines.
See: [MODINVSTOR-637](https://issues.folio.org/browse/MODINVSTOR-637).
Provide disclosure document.
Add checkmarks in disclosure document where appropriate.
Holdings has circulationNotes which allows for "source.personal".
The source.personal appears to allow for firstName and lastName at the very list.
The instance contributors may have middle names in them.
There are several structures with "notes" that are free form text.
These could potentially be used to store personal data.
One example is a holdings record.
The userIds are used and stored.
=> [MODINVSTOR-637] Add disclosure file.

ramls/inventory-view-instance.json, src/main/java/org/folio/persist/BoundWithRepository.java, src/main/java/org/folio/rest/impl/BoundWithPartAPI.java, src/main/java/org/folio/services/domainevent/BoundWithDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/BoundWithInstanceId.java, src/main/java/org/folio/services/instance/BoundWithPartService.java, src/main/java/org/folio/services/kafka/topic/KafkaTopic.java, src/main/resources/kafka-topics.json, src/main/resources/templates/db_scripts/instance-hr-item/instance-hr-item-view.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/BoundWithStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
`mod-search` must receive the isBoundWith attribute of instances in the Kafka message
- Add field `isBoundWith` to the view model and resource description
-  Create Kafka topic
-  Publish messages when BoundWithParts created/updated/deleted 
- Update integration tests to verify that the new field is included in the response
=> MODINVSTOR-867 publish isBoundWith in search results

ramls/authorities/authority.json
For correct MARC-to-Authority mapping several fields should be renamed:
* sftGeographicTerm -> sftGeographicName
* saftGeographicTerm -> saftGeographicName
=> MODINVSTOR-875 Rename fields in Authority schema

pom.xml, src/test/java/org/folio/rest/api/InventoryHierarchyViewTest.java, src/test/java/org/folio/rest/support/matchers/PostgresErrorMessageMatchers.java
Update the rmb version to prevent problems related to the connection pool.
* Upgrade vertx to v4.2.5
* Upgrade rmb to v33.2.6
* Upgrade folio-kafka-wrapper to v2.5.0-SNAPSHOT
[MODINVSTOR-878](https://issues.folio.org/browse/MODINVSTOR-878)
=> MODINVSTOR-878 Upgrade RMB/Vertx versions that contain fixes for the connection pool

src/main/java/org/folio/services/instance/InstanceEffectiveValuesService.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/services/instance/InstanceEffectiveValuesServiceTest.java
Any changes to the publicatioPeriod after the instance record has been created are being ignored.
- Create an instance record in the inventory with date of Publication populated
- Check if the publicationPeriod has been populate according to the rules from [MODINVSTOR-724](https://issues.folio.org/browse/MODINVSTOR-724)
- Edit the instance record by modifying date of Publication
publicationPeriod start and end date change according to the rules (as specified in [MODINVSTOR-724](https://issues.folio.org/browse/MODINVSTOR-724))
=> MODINVSTOR-874 publicationPeriod not changed after record update

src/main/java/org/folio/services/CallNumberUtils.java, src/test/java/org/folio/services/CallNumberUtilsTest.java
Populate Shelving order on the item record when the call number type is Other scheme.
- Current approach is to add the default behaviour if LcCallNumber or DeweyCallNumber parsers failed to recognize the input value
- Fix the bug with kept trailing space after DeweyCallNumber parsing
=> MODINVSTOR-877 Add Other schema support for effectiveShelvingOrder value

Jenkinsfile
This is a ResourceType file.
As alerted when authorities was first added.
See comment at [mod-inventory-storage/pull/690](https://github.com/folio-org/mod-inventory-storage/pull/690#issuecomment-958579789):
> Note that the file "./ramls/authorities/authority-collection.raml" is a RAML ResourceType and not a root-level RAML file. As such it should be in a directory "./ramls/rtypes" (similar to how raml-util/rtypes is organised). That directory would then be excluded by default from the detection of RAML files to be processed for validation and docs generation.
So specifically excluding this rtype file from processing with api-lint and api-doc.
=> MODINVSTOR-883 Exclude authority-collection.raml rtype from API lint and doc

src/main/java/org/folio/rest/impl/TenantRefAPI.java
Someone noticed that the module does not load
the new related-instance-types with other reference
data.  It looks like this is because it was not put in the 
tenantRefApi with the other reference directory names.
=> adding related reference types to list

src/main/resources/templates/db_scripts/changeUUIDCastInGetStatisticalCodesFunction.sql, src/main/resources/templates/db_scripts/schema.json
Jira: https://issues.folio.org/browse/MODINVSTOR-895
Remove the UUID casting within the WHERE clause of the accepted item ids array in order to prevent the failure of the entire getItemsAndHoldingsData SQL when the item statistical codes array contains bad data.
=> MODINVSTOR-895: bad data in item.statisticalCodeIds stops harvest

NEWS.md, src/main/java/org/folio/rest/support/HridManager.java, src/main/java/org/folio/rest/support/StatusUpdatedDateGenerator.java, src/main/java/org/folio/services/instance/InstanceService.java, src/test/java/org/folio/rest/api/BoundWithStorageTest.java
Original premise for this ticket was to only reduce database calls when retrieving HRID value. It appears that the database calls are a smaller fraction of the entire work done. More optimizations were made.
- Single call to retrieve hrid settings and hrid sequence value via UNION ALL select statement rather than database function
- Using a single thread safe date formatter rather than recreating a new one on each call to set status dates.
- Returning response to the api client before domain event publishing is complete.
=> MODINVSTOR-894 optimize create instance endpoint

src/test/java/org/folio/rest/api/ItemStorageTest.java
In some locales a and ä are the same therefore PostgreSQL may return them in any order.
Fix: Use a matcher that expects them in any order.
=> MODINVSTOR-904: Spurious fails in canSearchForItemsByBarcode

NEWS.md, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/AuthorityStorageTest.java
Fix "Optimistic locking" message does not return from back-end side
- enable 'failOnConflict' for authorities
[MODINVSTOR-909](https://issues.folio.org/browse/MODINVSTOR-909)
=> MODINVSTOR-909 Optimistic locking message does not return from back-end

src/main/java/org/folio/rest/support/HridManager.java, src/test/java/org/folio/rest/api/HridSettingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
A batch of 10 instances currently requires 10 SQL queries, each fetching
a single hrid.
Combining them into one SQL is faster:
Tested with the POST /instance-storage/batch/synchronous API and
a batch size of 10 instances.
The API response time on a system without load reduces
from 88 ms to 75 ms, this is -15 %.
The throughput on a system under load (many parallel requests to
this API) increases from 46 requests/second to 64 request/second
(= from 460 instance/second to 640 instances/second),
this is +39 %.
=> MODINVSTOR-908: Single HRID SQL query for batch (instance/holding/item)

src/main/java/org/folio/services/authority/AuthorityService.java, src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/instance/BoundWithPartService.java, src/main/java/org/folio/services/instance/InstanceService.java, src/main/java/org/folio/services/item/ItemService.java
When changing data domain events get published via Kafka.
After the domain event has been published mod-inventory-storage sends the response to its client.
This delay is not needed.
mod-inventory-storage should respond to its client and then publish the domain event to Kafka.
Performance gains:
From 25 ms to 18 ms for POST /item-storage/items API response time. (Caused by fetching item and holding to calculate the domain event.)
From 19 ms to 18 ms for POST /holdings-storage/holdings response time.
=> MODINVSTOR-911: Send Kafka message after returning API response

NEWS.md, pom.xml, src/main/resources/templates/db_scripts/inventory-hierarchy/correctGetUpdatedInstanceIdsView.sql, src/main/resources/templates/db_scripts/schema.json
Jira: https://issues.folio.org/browse/MODINVSTOR-913
Jira: https://issues.folio.org/browse/MODINVSTOR-914
Backport for mod-inventory-storage Lotus release that includes improvement [MODINVSTOR-913](https://issues.folio.org/browse/MODINVSTOR-913).
=> MODINVSTOR-913: Enhance inventory-hierarchy view to make it return instances by date search criteria that have holdings only - Lotus release

src/main/resources/templates/db_scripts/inventory-hierarchy/correctGetUpdatedInstanceIdsView.sql
Follow-up PR for [PR#774](https://github.com/folio-org/mod-inventory-storage/pull/774) with query performance improvement
[MODINVSTOR-912](https://issues.folio.org/browse/MODINVSTOR-912) - Enhance inventory-hierarchy view to make it return instances by date search criteria that have holdings only
=> MODINVSTOR-912 - Enhance inventory-hierarchy view to make it return instances by date search criteria that have holdings only

pom.xml
This makes mod-inventory-storage compile with OpenJDK 17.
=> Upgrade to lombok 1.18.24

README.MD
This PR verifies the api-doc tool generation of API documentation during merge to mainline. Some schemas that contain references to child schema using "folio:$ref" could not be dereferenced. The api-doc now temporarily replaces those references during processing.
See [FOLIO-3541](https://issues.folio.org/browse/FOLIO-3541).
=> FOLIO-3541 api-doc verify replace JSON schema folio:$ref

NEWS.md, src/main/resources/templates/db_scripts/schema.json
This script should have run for juniper, but had a bad version number (20.1.0).  To 
rectify, we are going to set it to run in the next version (25.0.0).  We will also issue 
a bugfix release for the current version (which will be 24.0.2).
=> MODINVSTOR-940:  Change when holdings effective location script runs

src/main/resources/templates/db_scripts/setEffectiveHoldingsLocation.sql
The migration script setEffectiveHoldingsLocation.sql sets the
effective location of all holdings. It should skip all holdings
that already have the effective location been set.
The effective location has a database index because it is a
foreign key to the location table:
https://github.com/folio-org/mod-inventory-storage/blob/v24.0.2/src/main/resources/templates/db_scripts/schema.json#L585-L611
Note that permanentLocationId is a required field:
https://github.com/folio-org/mod-inventory-storage/blob/v24.0.2/ramls/holdingsrecord.json#L371
Unit tests already exist in
src/test/java/org/folio/rest/api/EffectiveLocationMigrationTest.java
=> MODINVSTOR-949: Speed up setEffectiveHoldingsLocation.sql migration

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/instance-storage.raml, ramls/instance.json
It's needed to have information if a contributor is controlled by authority
Extend instance.contributors with authorityId
=> MODINVSTOR-950 Extend instance contributors schema with Authority ID

NEWS.md, ramls/authorities/authority.json
**Purpose**
It's needed to have information of an Authority Natural ID to use it in a link in $0 subfield of linked bib fields.
JIRA: https://issues.folio.org/browse/MODINVSTOR-955
**Approach**
- Extend authority schema with `naturalId` field
=> MODINVSTOR-955 Extend authority schema with Authority Natural ID

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/examples/instance-set.json, ramls/instance-set.json, ramls/instance-set.raml, ramls/instance-sets.json, src/main/java/org/folio/persist/InstanceRepository.java, src/main/java/org/folio/rest/impl/InstanceSetAPI.java, src/main/java/org/folio/rest/support/EndpointHandler.java, src/main/java/org/folio/services/instance/InstanceService.java, src/main/resources/templates/db_scripts/createInstanceSetView.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/InstanceRelationshipsTest.java, src/test/java/org/folio/rest/api/InstanceSetTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/support/http/InterfaceUrls.java
The "GET Instance Set by CQL" API ([MODINVSTOR-918](https://issues.folio.org/browse/MODINVSTOR-918)) speeds up mod-inventory-update: initial load is 30% faster, updates are more than 100% faster.
Therefore we need this back-ported to Morning Glory. It's low risk as the API is separate from other code.
=> MODINVSTOR-944: GET Instance Set by CQL - MG back-port

descriptors/ModuleDescriptor-template.json, ramls/authority-source-file.raml, ramls/authoritysourcefile-patch.json, ramls/authoritysourcefile.json, ramls/examples/authoritysourcefile.json, ramls/examples/authoritysourcefiles.json, reference-data/authority-source-files/AAT.json, reference-data/authority-source-files/FAST.json, reference-data/authority-source-files/GSAFD.json, reference-data/authority-source-files/LCCSH.json, reference-data/authority-source-files/LCFGT.json, reference-data/authority-source-files/LCGFT.json, reference-data/authority-source-files/LCMPT.json, reference-data/authority-source-files/LCNAF.json, reference-data/authority-source-files/LCSH.json, reference-data/authority-source-files/MeSH.json, reference-data/authority-source-files/RBMS.json, reference-data/authority-source-files/TGM.json, src/main/java/org/folio/persist/AuthoritySourceFileRepository.java, src/main/java/org/folio/rest/impl/AuthoritySourceFileAPI.java, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/AuthoritySourceFileAPITest.java, src/test/java/org/folio/rest/api/ReferenceTablesTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/entities/AuthoritySourceFile.java, src/test/java/org/folio/rest/support/HttpClient.java
**Purpose**
We need to populate a linked bib field $0 with a valid URI so that it's easier to support updating this information with rollout of additional capabilities. 
JIRA: https://issues.folio.org/browse/MODINVSTOR-952
**Approach**
- AuthoritySourceFile schema is updated with 'baseUrl' field
- AuthoritySourceFile schema is updated with 'source' field to distinguish pre-defined and custom records.
=> MODINVSTOR-952 Extend Pre-defined Authority Source file list to include a base URL

src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
There is a race condition with the "UPDATE" and the "CREATE" event.
This can be fixed by testing the last "UPDATE" event, not the last event.
=> MODINVSTOR-964: Intermittend even assert failures

src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java
Steps to Reproduce:
mvn test
Expected Results:
test phase of build succeeds
Actual Results:
About 70% of builds fail with `AsyncMigrationTest.canMigrateItemsInstances:92 » ConditionTimeout Condition wi...`
Complete error message:
```
09:06:55 [] [test_tenant] [] [mod_inventory_storage] ERROR DomainEventPublisher Unable to send event [{"type":"MIGRATION","tenant":"test_tenant","new":{"id":"c1c1ab9c-facd-464f-ac13-07cc57ead051","migrations":["publicationPeriodMigration","itemShelvingOrderMigration"],"affectedEntities":["ITEM","INSTANCE"],"published":[],"processed":[],"jobStatus":"In progress","submittedDate":"2022-10-17T07:06:55.264+00:00"}}]
org.apache.kafka.common.KafkaException: Producer closed while send in progress
at org.apache.kafka.clients.producer.internals.RecordAccumulator.append( …
```
=> MODINVSTOR-971: KafkaException: Producer closed while send in progress

descriptors/ModuleDescriptor-template.json
Remove the DB_*_READER environment variables from ModuleDescriptor, they are non-default values and fail the installation because most environments neither have a postgres-read host nor any other PostgreSQL reader host.
=> MODINVSTOR-974: Remove DB_*_READER env var from ModuleDescriptor

src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/test/java/org/folio/services/domainevent/CommonDomainEventPublisherTest.java
Streams are reused and closing a stream will make exceptions like java.lang.IllegalStateException:
Cannot perform operation after producer has been closed
=> Fix AsyncMigrationTest:92 ConditionTimeout MODINVSTOR-976

src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
About 30% of all builds fail because of at least one of these failures:
```
InstanceStorageTest.canDeleteInstancesByCql:487
Expected: is "DELETE"
but: was "CREATE"
```
```
HoldingsStorageTest.canDeleteHoldingsByCql:647
Expected: is "DELETE"
but: was "CREATE"
```
```
ItemStorageTest.canDeleteItemsByCql:2045
Expected: is "DELETE"
but: was "CREATE"
```
The current tests assert that the last event is the expected DELETE event. Due to the async nature of Kafka messages there might be a CREATE event.
Rewrite the test so that it succeeds if the expected DELETE event exists at any position in the event stream.
Write a hasRemoveEvent method that can be used with await().until(() -> hasRemoveEvent(...));
=> MODINVSTOR-977: hasRemoveEvent fixing sporadic unit test failures

src/main/resources/templates/db_scripts/addAuthoritySourceFiles.sql, src/main/resources/templates/db_scripts/schema.json
Populate default authority source files
* add a script to schema.json
=> MODINVSTOR-984 Authority source files reference data doesn't load during module upgrade

src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java
Following the work to improve stability of the tests that check published messages, I thought I'd experiment with what a streams implementation of getting the last / first message published was like.
I'd welcome thoughts on whether folks think this expresses intent better or worse than the current iterator based implementation.
(Note: work is needed to reduce the reliance on first / last message because the sequencing should be relied on, rather specific characteristics of the message should be to avoid ordering or concurrency issues)
=> Use streams for sorting received kafka messages MODINVSTOR-982

src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/support/JsonObjectMatchers.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/rest/support/messages/EventMessage.java, src/test/java/org/folio/rest/support/messages/InstanceEventMessage.java, src/test/java/org/folio/rest/support/messages/matchers/EventMessageMatchers.java
In order to remove the need for catching assertion exceptions and improve the stability of checking for published messages, replace the current use of assertions during awaitility with matcher composition.
The use of a `hasItem` matcher for checking the collection of received messages means that the test will pass when any of the messages matches the expectations, irrespective of ordering. This relies on the matching being sufficiently specific to not produce false matches.
As this is a new approach, the changes have been limited to only messages for creating and deleting instances.
* Inline current approach for checking for deleted message (for reference during replacement)
* introduce a type to represent an event message (to ease writing matchers rather than manipulating JSON)
* …
=> Use Awaitility Matcher when Creating and Deleting Instances MODINVSTOR-1001

reference-data/authority-source-files/LCNAF.json, src/main/resources/templates/db_scripts/schema.json, src/main/resources/templates/db_scripts/updateLCNAFAuthoritySourceFile.sql
Add ns as an identifying code for LCNAF Authority Source file
* Update reference data
* Add migration script
=> MODINVSTOR-988 Add ns as an identifying code for LCNAF Source file

src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/test/java/org/folio/rest/api/AuthorityStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/rest/support/messages/AuthorityEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java
A follow on from #862 and #863
In order to remove the need for catching assertion exceptions and improve the stability of checking for published messages, replace the current use of assertions during awaitility with matcher composition.
The use of a `hasItem` matcher for checking the collection of received messages means that the test will pass when any of the messages matches the expectations, irrespective of ordering. This relies on the matching being sufficiently specific to not produce false matches.
The previous changes has moved all of the instance messages to this new approach. This change moves the authority message checks to the new approach.
* move (and rename) methods for authority messages to separate class
* use matcher with awaitility for each check
* remove additional …
=> Apply awaitility matchers to authority messages MODINVSTOR-1001

src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java, src/test/java/org/folio/rest/support/messages/HoldingsEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/matchers/EventMessageMatchers.java
A follow on from #862 , #863 and #865
In order to remove the need for catching assertion exceptions and improve the stability of checking for published messages, replace the current use of assertions during awaitility with matcher composition.
The use of a `hasItem` matcher for checking the collection of received messages means that the test will pass when any of the messages matches the expectations, irrespective of ordering. This relies on the matching being sufficiently specific to not produce false matches.
The previous changes has moved all of the instance and authority messages to this new approach. This change moves holdings message checks to the new approach.
* move (and rename) methods for holdings messages to separate class
* use matcher with awaitility for each check
* remove …
=> Use awaitility matchers for checking holdings messages MODINVSTOR-1001

src/test/java/org/folio/rest/api/BoundWithStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/messages/BoundWithEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/ItemEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/matchers/EventMessageMatchers.java
A follow on from #862 , #863, #865, #867 and #869
In order to remove the need for catching assertion exceptions and improve the stability of checking for published messages, replace the current use of assertions during awaitility with matcher composition.
The use of a `hasItem` matcher for checking the collection of received messages means that the test will pass when any of the messages matches the expectations, irrespective of ordering. This relies on the matching being sufficiently specific to not produce false matches.
The previous changes has moved all of the instance, authority, holdings and item messages to this new approach. This change moves bound with message checks to the new approach.
The check for update messages deliberately DOES NOT check the `old` representation of the …
=> Use awaitility matchers for bound with messages MODINVSTOR-1001

src/test/java/org/folio/rest/api/AuthorityStorageTest.java, src/test/java/org/folio/rest/api/BoundWithStorageTest.java, src/test/java/org/folio/rest/api/DereferencedItemStorageTest.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceDomainEventTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/IterationJobRunnerTest.java, src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java, src/test/java/org/folio/rest/api/SampleDataTest.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/kafka/AggregateMessageCollector.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/kafka/GroupedCollectedMessages.java, src/test/java/org/folio/rest/support/kafka/GroupedMessageCollector.java, src/test/java/org/folio/rest/support/kafka/MessageCollectingTopicConsumer.java, src/test/java/org/folio/rest/support/kafka/MessageCollector.java, src/test/java/org/folio/rest/support/kafka/TopicFilterIngMessageCollector.java, src/test/java/org/folio/rest/support/kafka/VertxMessageCollectingTopicConsumer.java, src/test/java/org/folio/rest/support/messages/AuthorityEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/BoundWithEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/HoldingsEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/InstanceEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/ItemEventMessageChecks.java
A follow on from #862, #863, #865, #867, #869 and #870
Now that most of the assertions around the receiving of Kafka messages has been moved to Awaitility methods that use Hamcrest matchers, the fake Kafka consumer can be reworked and, hopefully, simplified as much of the logic has been moved.
Initially, these changes included using a separate consumer for each topic, however that seems to have had a significant impact on build times and so was changed back to a single consumer.
* convert received messages from kafka consumer records before retaining them for assertions
* remove the checks for messages that occur out of timestamp order because ordering is no longer relied on in assertions
* Extract topic consumer to a separate class
* Extract message collecting into set of separate …
=> Rework fake kafka consumer MODINVSTOR-1001

src/test/java/org/folio/rest/api/AbstractInstanceRecordsAPITest.java, src/test/java/org/folio/rest/api/DereferencedItemStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/InventoryViewTest.java, src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java, src/test/java/org/folio/rest/api/SampleDataTest.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/utility/LocationUtility.java
A follow on from #862, #863, #865, #867, #869, #870, #872
Final (hopefully) pull request for removing throwing or catching assertion errors.
* Allow exceptions to bubble up to cause test failures
* Replace throwing assertion errors with separate assertions
* Also includes removing unnecessary removal of captures messages (that should've been part of previous PR)
=> Remove rest of assertion error catching MODINVSTOR-1001

ramls/bound-with-part.raml, src/main/java/org/folio/rest/impl/BoundWithAPI.java, src/test/java/org/folio/rest/api/BoundWithStorageTest.java
- If the main holdings ID (the one directly linked to the bound-with item) is not included in the composite bound-with request, the API will include it
- Unless the main holdings ID would then be the only part of the bound-with, in which case it will we left out whether it was provided or not. If it was inserted as the lone part of a bound-with through the bound-with-parts API (which will still allow this) it would be removed by a subsequent composite request as described.
=> Bound-with: Enforce main holdings ID inclusion (MODINVSTOR-1032)

descriptors/ModuleDescriptor-template.json, src/test/java/org/folio/rest/api/AsyncMigrationTest.java
[MODINVSTOR-1048](https://issues.folio.org/browse/MODINVSTOR-1048) - Handle deleted holdings/items in harvest (implementation)
Use minor version of inventory-hierarchy interface to avoid breaking change for mod-rtac module.
=> MODINVSTOR-1048 - Handle deleted holdings/items in harvest (implementation)

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.MD, ramls/contributor-type.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODINVSTOR-1065 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml, src/main/java/org/folio/services/CallNumberUtils.java, src/test/java/org/folio/services/CallNumberUtilsTest.java
Add browse option for National Library of Medicine (NLM) call number type and for this implement normalization for NLM that follows the normalization of LC classification:
- NLM call numbers have the item call number type "National Library of Medicine classification"
- LC call numbers have the item call number type "Library of Congress classification"
_Support browsing by NLM call number type_
_Implements normalization for NLM that follows the normalization of LC classification_
_Closes: [MODINVSTOR-1066](https://issues.folio.org/browse/MODINVSTOR-1066)_
=> MODINVSTOR-1066: add browse option for NLM call number type

descriptors/ModuleDescriptor-template.json, ramls/electronic-access-relationship.raml, ramls/electronicaccessrelationship.json, ramls/examples/electronicaccessrelationship.json, ramls/examples/electronicaccessrelationships.json, ramls/examples/loantype.json, ramls/examples/loantypes.json, ramls/loan-type.raml, ramls/loantype.json, src/test/java/org/folio/rest/api/LoanTypeTest.java, src/test/java/org/folio/rest/api/ReferenceTablesTest.java
Resolves [MODINVSTOR-1080](https://issues.folio.org/browse/MODINVSTOR-1080) Modify inventory dtos to include source field
This table describes what setting we are going to implement in Consortium Manager:
https://wiki.folio.org/display/FOLIJET/Consortium+manager+settings
For _mod-inventory-storage_ they are _loan type_ and _electronic access relationship_. (All other already have 'source' field.)
Setting created in Consortium Manager will have value _'Consortium'_ and we will add validation to prevent updating them
=> MODINVSTOR-1080 Modify inventory dtos to include source field

ramls/instance.json, src/main/java/org/folio/services/instance/InstanceService.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
When a local instance is promoted to a Shared Instance in the central tenant, the local instance will be converted to a Shadow instance. The details of the Shadow Instance will mirror the Shared Instance, including its HRID.
Allow HRID to be updated when transitioning to a Shadow Instance only.
[MODINVSTOR-1073](https://issues.folio.org/browse/MODINVSTOR-1073)
=> MODINVSTOR-1073: Convert Local Instance to Shared Instance

src/main/java/org/folio/services/item/ItemService.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
Resolves: [MODINVSTOR-1093](https://issues.folio.org/browse/MODINVSTOR-1093) Data import: circulation notes created via import cause blank references, rendering items uneditable within the UI
**Overview:** Data import field mapping profiles for items allow the addition/update/removal of circulation notes. However, when adding circulation notes to items via data import, null ID values are added to the circulation notes. This prevents records from being editable in the UI after the fact. Once the circulation notes are removed via import or API, the records are editable again. 
**Approach**
Generate id for _circulationNote_ if empty, use existing otherwise
**Affected endpoints**
- POST /item-storage/items
- PUT /item-storage/items
- POST /item-storage/batch/synchronous
- POST …
=> [MODINVSTOR-1093] Data import: circulation notes created via import cause blank references, rendering items uneditable within the UI

src/main/resources/templates/db_scripts/populateCirculationNoteIds.sql, src/main/resources/templates/db_scripts/schema.json
**Resolves**
[MODINVSTOR-1096](https://issues.folio.org/browse/MODINVSTOR-1096) Items with multiple circulation notes that do not have an id cannot be updated
**Approach**
See Analysis in [MODFISTO-215](https://issues.folio.org/browse/MODFISTO-215) ticket, and [PR](https://github.com/folio-org/mod-finance-storage/pull/214/files):
- Why we need _uuid-ossp extension_
- When we can use _uuid_generate_v4()_ or _uuid_generate_v5()_
=> [MODINVSTOR-1096] Items with multiple circulation notes that do not have an id cannot be updated

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/holding/HoldingsService.java, src/test/java/org/folio/rest/InstallUpgradeIT.java, src/test/java/org/folio/rest/api/BoundWithStorageTest.java, src/test/java/org/folio/rest/api/EffectiveLocationMigrationTest.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceDomainEventTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java, src/test/java/org/folio/rest/api/RecordBulkTest.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/support/http/ResourceClient.java
to provide the creation of corresponding shadow instance upon creation of holdings record on a shared instance
* create a shadow instance on the local tenant through the consortium sharing process if such instance doesn't exist with the instance id specified in the received holding to be created
* add and update tests
[MODINVSTOR-1103](https://issues.folio.org/browse/MODINVSTOR-1103)
=> MODINVSTOR-1103 - Ad hoc Shadow Instance creation when adding a Holdings to a Shared Instance

src/main/java/org/folio/services/holding/HoldingsService.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java
Not run consortium logic for tenant which not have appropriate system property to fix the next problem during the load of sample data: 
`Tenant operation failed for module mod-inventory-storage-26.1.0-SNAPSHOT.904: GET http://mod-inventory-storage/holdings-storage/holdings/65032151-39a5-4cef-8810-5350eb316300 returned status 404: Not found POST http://mod-inventory-storage/holdings-storage/holdings returned status 500: Error loading consortium data, tenantId: 'aqa' response status: '403', body: 'Access for user 'UNDEFINED_USER_10.0.75.227:53462_2023-10-04T09:57:04.825+0000' (null) requires permission: user-tenants.collection.get'`
Added system property **consortium.enabled**, which defines if we should execute consortium logic
=> [MODINVSTOR-1114] Add a new system property to define if consotrium process should be executed

pom.xml, src/main/java/org/folio/services/caches/ConsortiumDataCache.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/services/caches/ConsortiumDataCacheTest.java
Ignore permission errors during load of consortium data to allow supertenant create tenants at test envs
Ignore permission errors during load of consortium data, skip further ECS logic
=> [MODINVSTOR-1114] Not fail future if user not have permissions to load consortium data

PULL_REQUEST_TEMPLATE.md, README.MD, src/main/java/org/folio/InventoryKafkaTopic.java, src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
Add support for controlling a number of partitions for topics created on module startup.
Add `KAFKA_DOMAIN_TOPIC_NUM_PARTITIONS` env variable with default value = `50`
https://issues.folio.org/browse/MODINVSTOR-1131
=> fix(domain-events): create env variable to control number of partitions for topics

src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java
_Fix Sporadic test failure: ReindexJobRunnerTest.canGetAllInstancesReindexJobs_
It turned out that test methods in `org.folio.rest.api.ReindexJobRunnerTest` are order dependent. And in some cases `ReindexJobRunnerTest#canGetAllInstancesReindexJobs` test may go before `ReindexJobRunnerTest#canStartInstanceReindex` test.
So, to avoid such behavior we should call `InstanceReindexFixture#postReindexJob` in each test separately.
[_MODINVSTOR-1092_](https://issues.folio.org/browse/MODINVSTOR-1092)
=> MODINVSTOR-1092 Sporadic test failure: ReindexJobRunnerTest.canGetAllInstancesReindexJobs

pom.xml
Upgrade snappy-java from 1.1.8.1 to 1.1.10.5 fixing four security vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2023-43642
* https://nvd.nist.gov/vuln/detail/CVE-2023-34455
* https://nvd.nist.gov/vuln/detail/CVE-2023-34453
* https://nvd.nist.gov/vuln/detail/CVE-2023-34454
=> MODINVSTOR-1139: Upgrade snappy-java 1.1.8.1 to 1.1.10.5 fixing vulns

descriptors/ModuleDescriptor-template.json, ramls/contributor-name-type.raml, ramls/contributornametype.json, ramls/electronicaccessrelationship.json, ramls/examples/contributornametype.json, ramls/examples/contributornametypes.json, ramls/examples/electronicaccessrelationship.json, ramls/examples/electronicaccessrelationships.json, ramls/examples/loantype.json, ramls/examples/loantypes.json, ramls/holdings-sources/holdingsRecordsSource.json
https://issues.folio.org/browse/MODINVSTOR-1143
Add 'source' field to Contributor Name type, also enum of allowed values extended with 'consortium' value for Holdings Record Source.
Also there was some improvements with examples(here is original PR https://github.com/folio-org/mod-inventory-storage/pull/912/files ) to remove unused options and remain only 'consortium' and 'local', because only these 2 values used in mod-consortia [Link  ](https://github.com/folio-org/mod-consortia/blob/master/src/main/java/org/folio/consortia/utils/HelperUtils.java#L10)
https://issues.folio.org/browse/MODCON-122
https://issues.folio.org/browse/MODCON-121
=> MODINVSTOR-1143. Add source field to contributor name type

NEWS.md, pom.xml
Do not delete Kafka topics on postTenant if collection topics is enabled
Updated `folio-kafka-wrapper` to v3.1.1
https://folio-org.atlassian.net/browse/MODINVSTOR-1192
=> fix: Do not delete Kafka topics on postTenant if collection topics is enabled

NEWS.md, pom.xml, src/main/java/org/folio/services/consortium/ShadowInstanceSynchronizationHandler.java, src/test/java/org/folio/rest/api/AsyncMigrationTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java, src/test/java/org/folio/rest/api/ItemEffectiveLocationTest.java, src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/java/org/folio/rest/api/TestBase.java, src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java, src/test/java/org/folio/rest/impl/BaseIntegrationTest.java, src/test/java/org/folio/rest/impl/BaseReferenceDataIntegrationTest.java, src/test/java/org/folio/rest/impl/CallNumberTypeApiTest.java, src/test/java/org/folio/rest/impl/LocationIT.java
Fix unintended update of instance records \_version (optimistic locking) whenever any of its holdings or items are created, updated or deleted.
- Upgrade RMB from 35.2.0 to 35.2.1
- Fix test setup in CallNumberApiTest to make it independent of test execution order
- Remove CallNumberApiTest to avoid duplicate run (JUnit automatically runs it)
- Fix incorrect JsonObject.mapFrom usage
https://folio-org.atlassian.net/browse/MODINVSTOR-1186
=> MODINVSTOR-1186: RMB 35.2.1 fixing unintended optimistic locking

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/service-point.raml, ramls/servicepoint.json, src/test/java/org/folio/rest/api/ServicePointTest.java
Covers: [MODINVSTOR-1179](https://folio-org.atlassian.net/browse/MODINVSTOR-1179)
Add a new boolean field ecsRequestRouting to the service point schema. 
It shouldn't be required, default value is false.
=> MODINVSTOR-1179 Add ecsRequestRouting field to service point schema

descriptors/ModuleDescriptor-template.json, ramls/service-point.raml, src/main/java/org/folio/rest/impl/ServicePointApi.java, src/test/java/org/folio/rest/api/ServicePointTest.java, src/test/java/org/folio/utility/LocationUtility.java
Return ECS routing service points in response to `GET /service-points` only when explicitly requested.
[MODINVSTOR-1219](https://github.com/folio-org/mod-inventory-storage/compare/MODINVSTOR-1219)
Introduce a new query parameter `includeRoutingServicePoints` to `GET /service-points` endpoint. Set this flag to `false` by default. Return ECS routing service points only when it is explicitly set to `true`.
=> MODINVSTOR-1219: Do not return routing service points by default

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/examples/retrieveEntitiesDto.json, ramls/holdings-storage.raml, ramls/instance-storage.raml, ramls/retrieveEntitiesDto.json, src/main/java/org/folio/rest/impl/HoldingsStorageApi.java, src/main/java/org/folio/rest/impl/InstanceStorageApi.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
When requesting `instance-storage/instance` or `holding-storage/holdings` API, a `414` error sometimes occurs if the query parameter contains too many characters
Add POST requests `instance-storage/instances/retrieve` and `holding-storage/holdings/retrieve` and pass values in the request body
https://folio-org.atlassian.net/browse/MODINVSTOR-1223
=> MODINVSTOR-1223 Implement a POST request to get holdings and instances

NEWS.md, src/test/java/org/folio/rest/InstallUpgradeIT.java, src/test/java/org/folio/rest/impl/BaseIntegrationTest.java, src/test/java/org/folio/services/kafka/topic/KafkaTopicsExistsTest.java, src/test/java/org/folio/utility/KafkaUtility.java
https://folio-org.atlassian.net/browse/MODINVSTOR-1251
Upgrade from deprecated org.testcontainers.containers.KafkaContainer to org.testcontainers.kafka.KafkaContainer, see https://java.testcontainers.org/modules/kafka/
Upgrade from confluentinc/cp-kafka:5.4.3 and confluentinc/cp-kafka:7.0.3 to apache/kafka-native:3.8.0, see https://hub.docker.com/r/apache/kafka-native
Fix KafkaTopicsExistsTest to await topics. The test order may put load on Kafka resulting in delays until topics appears. 900 retries is too small.
Upgrade Kafka testcontainers.
kafka-native has smaller image size (47 MB compared to 446 MB or 382 MB), starts faster, and uses less memory.
Fix race condition in KafkaTopicsExistsTest.
Upgrade from org.testcontainers.containers.KafkaContainer to …
=> MODINVSTOR-1251: kafka.KafkaContainer, apache/kafka-native:3.8.0

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/caches/ConsortiumDataCache.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/services/caches/ConsortiumDataCacheTest.java
Properly fix https://folio-org.atlassian.net/browse/MODINVSTOR-1114
- Add user-tenants.collection.get to all ECS APIs
- Remove code that ignored forbidden response at consortium data cache
https://folio-org.atlassian.net/browse/MODINVSTOR-1253
=> [MODINVSTOR-1253] Add user-tenants.collection.get to all ECS APIs

NEWS.md, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/caches/ConsortiumDataCache.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/services/caches/ConsortiumDataCacheTest.java
https://folio-org.atlassian.net/browse/MODINVSTOR-1260
Add user-tenants.collection.get permission to POST /_/tenant API
Add the permission as "modulePermissions" in module descriptor.
https://folio-org.atlassian.net/browse/MODINVSTOR-1114
https://folio-org.atlassian.net/browse/MODINVSTOR-1253
https://folio-org.atlassian.net/browse/MODINVSTOR-1260
=> MODINVSTOR-1260: Add user-tenants.collection.get permission to POST /_/tenant API

src/main/java/org/folio/persist/HoldingsRepository.java, src/main/java/org/folio/persist/ItemRepository.java, src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/ItemDomainEventPublisher.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/item/ItemService.java
If database contains invalid data then the range publishing failed due to deserialization issue.
fetch maps instead of object + add instanceId into item
=> fix(inventory-reindex-records): fetch maps instead of object + add instanceId into item

README.MD, descriptors/ModuleDescriptor-template.json, src/main/java/org/folio/services/domainevent/CommonDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java
Make reindex kafka producer maxRequestSize configurable
- Parse env or use default for kafka config in reindex publisher
[MODINVSTOR-1265](https://folio-org.atlassian.net/browse/MODINVSTOR-1265)
=> feat(inventory-reindex-records): Make reindex kafka producer maxRequestSize configurable

NEWS.md, ramls/subject-source.json, reference-data/subject-sources/CanadianSubjectHeadings.json, reference-data/subject-sources/LibraryofCongressChildrensandYoungAdultsSubjectHeadings.json, reference-data/subject-sources/LibraryofCongressSubjectHeadings.json, reference-data/subject-sources/MedicalSubjectHeadings.json, reference-data/subject-sources/NationalAgriculturalLibrarysubjectauthorityfile.json, reference-data/subject-sources/Repertoiredevedettes-matiere.json, reference-data/subject-sources/Sourcenotspecified.json, reference-data/subject-types/Chronologicalterm.json, reference-data/subject-types/Corporatename.json, reference-data/subject-types/Curriculumobjective.json, reference-data/subject-types/Facetedtopicalterms.json, reference-data/subject-types/Function.json, reference-data/subject-types/Genreform.json, reference-data/subject-types/Geographicname.json, reference-data/subject-types/Hierarchicalplacename.json, reference-data/subject-types/Meetingname.json, reference-data/subject-types/Namedevent.json, reference-data/subject-types/Occupation.json, reference-data/subject-types/Personalname.json, reference-data/subject-types/Topicalterm.json, reference-data/subject-types/Typeofentityunspecified.json, reference-data/subject-types/Uncontrolled.json, reference-data/subject-types/Uniformtitle.json, src/main/resources/templates/db_scripts/addSubjectSources.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/SubjectSourceTest.java, src/test/java/org/folio/rest/impl/SubjectSourcesIT.java
Add codes to Subject sources
- Extend schema of Subject source to contain code (code should be unique)
- Remove reference data “specified in subfiled $2”
- Add codes to existing as ref data Subject sources (find corresponding values in [Subject Heading and Term Source Codes: Source Codes for Vocabularies, Rules, and Schemes (Network Development and MARC Standards Office, Library of Congress)](https://www.loc.gov/standards/sourcelist/subject.html) )
https://folio-org.atlassian.net/browse/MODINVSTOR-1264
=> [MODINVSTOR-1264] Add codes to Subject sources

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/instance-iteration.raml, ramls/instance-set.raml, ramls/instance-storage-batch.raml, ramls/instance-storage.raml, ramls/instance-sync-unsafe.raml, ramls/instance-sync.raml, ramls/instance.json, ramls/inventory-view.raml, src/main/resources/templates/db_scripts/publication-period/migratePublicationPeriod.sql, src/main/resources/templates/db_scripts/schema.json, src/test/java/org/folio/rest/api/PublicationPeriodMigrationTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java, src/test/resources/instances/bulk/bulkInstanceRepresentation.json, src/test/resources/instances/bulk/expectedInstance.json
[MODINVSTOR-1232](https://folio-org.atlassian.net/browse/MODINVSTOR-1232) Currently in the Instance schema, there is a field for publication date. However, this data originates from an uncontrolled string in variable fields of the MARC record. The dates in the 008 are more consistently formatted, and are more useful for certain materials like serials. Previously, we implemented sortable properties (publicationPeriod.start/publicationPeriod.end) that are parsed from the publication date field. We need to break this relationship, and instead make the source of that data the 07-14 from the 008. We need to determine how to migrate data from these MARC fields as well as existing publication date field for FOLIO source records.
Create migration script that will migrate instances:
1. Move value …
=> feat(instance-dates): Migration: Population of Date type, Date 1, and Date 2 for FOLIO source records

NEWS.md, pom.xml, src/test/java/org/folio/rest/api/InstanceStorageInstancesBulkApiTest.java
https://folio-org.atlassian.net/browse/MODINVSTOR-1272
0.11.3 has been released 2020-06-28:
https://github.com/localstack/localstack/releases/tag/v0.11.3 0.11.3 has an image size of 454 MB:
https://hub.docker.com/r/localstack/localstack/tags?name=0.11.3
s3-latest has been released 2024-10-03 and has an image size of 108 MB: https://hub.docker.com/r/localstack/localstack/tags?name=0.11.3
This reduces the image size from 454 MB to 108 MB.
For the s3 only image there's no version tag, only the -latest tag.
Upgrade 4 year old localstack.
Reduce localstack image size.
Upgrade localstack from 0.11.3 to s3-latest (=3.8.0)
=> MODINVSTOR-1272: Upgrade localstack from 0.11.3 to s3-latest (=3.8.0)

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
To support automatic capabilities creation and keep FOLIO permission usage consistent, it is suggested that all module descriptors be reviewed and inconsistencies in permission namings and usage be fixed.
Add module descriptor validator plugin and fix the issue with permission names
=> build: add folio-module-descriptor-validator plugin and fix the permission names

descriptors/ModuleDescriptor-template.json
https://folio-org.atlassian.net/browse/MODINVSTOR-1270
During implementing https://github.com/folio-org/mod-inventory-storage/pull/1098 new validation is added that fetches /user-tenant endpoint.
Need to add appropriate module permissions
=> MODINVSTOR-1270. Add required module permissions

NEWS.md, pom.xml, ramls/bulkUpsertRequest.json, src/main/java/org/folio/rest/impl/InstanceBatchSyncApi.java, src/main/java/org/folio/rest/impl/InstanceBatchSyncUnsafeApi.java, src/main/java/org/folio/services/BulkProcessingContext.java, src/main/java/org/folio/services/batch/BatchOperationContext.java, src/main/java/org/folio/services/batch/BatchOperationContextFactory.java, src/main/java/org/folio/services/bulkprocessing/AbstractEntityS3Service.java, src/main/java/org/folio/services/bulkprocessing/InstanceS3Service.java, src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/instance/InstanceService.java, src/main/java/org/folio/services/item/ItemService.java, src/test/java/org/folio/rest/api/InstanceStorageInstancesBulkApiTest.java, src/test/java/org/folio/rest/support/BulkProcessingErrorFileWriterTest.java, src/test/java/org/folio/services/BulkProcessingContextTest.java
Modify endpoint for bulk instances upsert with publish events flag
Add new field to bulk schema.
https://folio-org.atlassian.net/browse/MODINVSTOR-1283
=> MODINVSTOR-1283 Modify endpoint for bulk instances upsert with publish events flag

NEWS.md, src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/ItemDomainEventPublisher.java, src/main/java/org/folio/services/holding/HoldingsService.java, src/main/java/org/folio/services/item/ItemService.java, src/test/java/org/folio/rest/api/HoldingsStorageTest.java, src/test/java/org/folio/rest/support/kafka/FakeKafkaConsumer.java, src/test/java/org/folio/rest/support/messages/HoldingsEventMessageChecks.java, src/test/java/org/folio/rest/support/messages/ItemEventMessageChecks.java
[MODINVSTOR-1281](https://folio-org.atlassian.net/browse/MODINVSTOR-1281) Currently, mod-search has an issue with processing events received from  the mod-inventory-storage  after creating a list of holdings for one Instance via the POST /holdings-storage/batch/synchronous endpoint.
The mod-inventory-storage publishes the list of events on creating holdings for an instance with the instanceId publishing key. So the list of events with the same instanceId publishing key are published.
The mod-search consumes events, groups them by key and processes only the one event, so in this case the rest events with the same instanceId key will not be processed and the data will not get into the holding table of the mod-search module.
The same issue with Items : POST /item-storage/batch/synchronous …
=> feat(publishing-events): change Kafka event publishing keys for holdings and items.

NEWS.md, README.MD, descriptors/ModuleDescriptor-template.json, pom.xml, ramls/service-point.raml, ramls/servicepoint.json, src/main/java/org/folio/rest/impl/InitApiImpl.java, src/main/java/org/folio/rest/impl/ServicePointApi.java, src/main/java/org/folio/services/consortium/ServicePointSynchronizationVerticle.java, src/main/java/org/folio/services/consortium/handler/ServicePointSynchronizationCreateHandler.java, src/main/java/org/folio/services/consortium/handler/ServicePointSynchronizationDeleteHandler.java, src/main/java/org/folio/services/consortium/handler/ServicePointSynchronizationHandler.java, src/main/java/org/folio/services/consortium/handler/ServicePointSynchronizationUpdateHandler.java, src/main/java/org/folio/services/consortium/processor/ServicePointSynchronizationCreateEventProcessor.java, src/main/java/org/folio/services/consortium/processor/ServicePointSynchronizationDeleteEventProcessor.java, src/main/java/org/folio/services/consortium/processor/ServicePointSynchronizationEventProcessor.java, src/main/java/org/folio/services/consortium/processor/ServicePointSynchronizationUpdateEventProcessor.java, src/main/java/org/folio/services/domainevent/ServicePointDomainEventPublisher.java, src/main/java/org/folio/services/domainevent/ServicePointEventType.java, src/main/java/org/folio/services/servicepoint/ServicePointService.java, src/main/java/org/folio/utils/Environment.java, src/test/java/org/folio/rest/api/ServicePointSynchronizationVerticleTest.java, src/test/java/org/folio/rest/api/ServicePointTest.java, src/test/java/org/folio/services/consortium/processor/ServicePointSynchronizationEventProcessorTest.java, src/test/java/org/folio/utility/LocationUtility.java
Resolves: [MODINVSTOR-1294](https://folio-org.atlassian.net/browse/MODINVSTOR-1294)
=> MODINVSTOR-1294 Release 28.0.2

NEWS.md, src/main/java/org/folio/persist/InstanceRepository.java, src/main/java/org/folio/services/ResponseHandlerUtil.java, src/main/java/org/folio/services/instance/InstanceService.java, src/test/java/org/folio/rest/api/AsyncMigrationTest.java, src/test/java/org/folio/rest/api/InstanceStorageTest.java
[MODINVSTOR-1299](https://folio-org.atlassian.net/browse/MODINVSTOR-1299) update rollback mechanism for instances when linking/unlinking with subjects is failed.
hotfix pr to resolve the issue with failing hourly builts 
> Tenant operation failed for module mod-inventory-storage-28.1.0-SNAPSHOT.1060: GET http://10.36.1.221:9151/instance-storage/instances/e6bc03c6-c137-4221-b679-a7c5c31f986c returned status 404: null POST http://10.36.1.221:9151/instance-storage/instances returned status 500: Timeout for DB_HOST:DB_PORT=10.36.1.221:5432
* use atomic transactions
* update tests
=> HOTFIX: MODINVSTOR-1299 update rollback mechanism for instances when linking/unlinking with subjects is failed.

NEWS.md, src/main/java/org/folio/persist/AbstractRepository.java, src/main/java/org/folio/services/consortium/ConsortiumServiceImpl.java, src/main/java/org/folio/services/holding/HoldingsService.java
[MODINVSTOR-1354](https://folio-org.atlassian.net/browse/MODINVSTOR-1354)
In ECS when Holdings is created on a member tenant associated with a shared Instance that exists on a central tenant, a shadow copy of the Instance should be created on the member to link the Holdings, unless it already exists. To check if the Instance exists it is unnecessary to retrieve the whole object, the operation could be optimized by merely checking that object with such id exists.
=> MODINVSTOR-1354 Optimize check for existing shadow Instance before creating it

src/main/resources/templates/db_scripts/populateDiscoverySuppressIfNotSet.sql
Populating discoverySuppress, if not installed, is slow during module enable.
Updated WHERE condition to use the index.
[MODINVSTOR-1357](https://folio-org.atlassian.net/browse/MODINVSTOR-1357)
=> MODINVSTOR-1357: query updated to use index

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/instance.json, src/main/java/org/folio/rest/support/InstanceBulkProcessingUtil.java, src/test/java/org/folio/rest/support/InstanceBulkProcessingUtilTest.java
Add "deleted" field to Instance schema
[_List any Jira issues related to this pull request._](https://folio-org.atlassian.net/browse/MODINVSTOR-1342)
=> MODINVSTOR-1342: Add "deleted" field to Instance schema

NEWS.md, src/main/resources/templates/db_scripts/oaipmh/createDiscoverySuppressSourceIndex.sql, src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-1377](https://folio-org.atlassian.net/browse/MODINVSTOR-1377) - mod-oai-pmh - new indexes
The instance_discoverysuppress_source_idx should be applied to both fields: discoverySuppress and source. This allows significantly improve the mentioned query performance.
=> MODINVSTOR-1377 - mod-oai-pmh - new indexes

NEWS.md, src/main/java/org/folio/services/consortium/ShadowInstanceSynchronizationHandler.java
to fix issue where changes are intermittently not propagated to shadow instances on member tenants after a shared instance update
* create a copy of the instance to prevent side effects between member tenants during instance version population
[MODINVSTOR-1393](https://issues.folio.org/browse/MODINVSTOR-1393)
=> MODINVSTOR-1393 - Suppress shared FOLIO Instance from discovery in Central tenant does not always propagate to record in Member tenant

NEWS.md, src/main/java/org/folio/services/instance/InstanceService.java
[MODINVSTOR-1427](https://folio-org.atlassian.net/browse/MODINVSTOR-1427) - Random error when opening orders
When an instance is created, the result was returned before the transaction was released. As a consequence, creating holdings afterwards referencing the instance was failing because of the foreign key on the instance id. This only happened, seemingly at random, on fast computers. The error was sometimes happening 10 times while processing mod-orders integration tests, when orders were opened and holdings were created after the instance.
This fix simply moves `onSuccess` and `onFailure` after the transaction block.
[MODINVSTOR-1299](https://folio-org.atlassian.net/browse/MODINVSTOR-1299) - [PR](https://github.com/folio-org/mod-inventory-storage/pull/1127)
=> [MODINVSTOR-1427] Fixed instance creation

NEWS.md, src/main/java/org/folio/persist/IterationJobRepository.java, src/main/java/org/folio/services/iteration/IterationJobRunner.java, src/test/java/org/folio/persist/IterationJobRepositoryTest.java, src/test/java/org/folio/rest/api/StorageTestSuite.java
[MODINVSTOR-1450](https://folio-org.atlassian.net/browse/MODINVSTOR-1450) Fix inconsistent "messagesPublished" updates caused by asynchronous execution in IterationJobRunner.
Due to asynchronous execution, there is an issue where the `messagesPublished` field may be overwritten with an outdated value. This can occur when the job status has already been marked as `COMPLETED` and the corresponding `messagesPublished` value has been stored, but the `logJobDetails` method finishes execution afterward and writes an outdated value to the same field.
If the job status is marked as `COMPLETED`, no further updates to the `messagesPublished` field are applied.
Logs from the test that identified the issue::
https://jenkins-aws.indexdata.com/job/folio-org/job/mod-inventory-storage/job/MODINVSTOR-987/1 …
=> fix(iteration-job-runner) Fix inconsistent "messagesPublished" updates caused by asynchronous execution in IterationJobRunner.

NEWS.md, descriptors/ModuleDescriptor-template.json, ramls/examples/items_patch.json, ramls/item-storage.raml, ramls/item-storage/itemPatch.json, ramls/itemspatch.json, src/main/java/org/folio/persist/HoldingsRepository.java, src/main/java/org/folio/persist/ItemRepository.java, src/main/java/org/folio/rest/impl/ItemStorageApi.java, src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java, src/main/java/org/folio/services/item/ItemService.java, src/main/java/org/folio/services/item/ItemUtils.java, src/main/java/org/folio/services/item/PatchData.java, src/test/java/org/folio/rest/api/ItemStorageTest.java, src/test/java/org/folio/rest/support/HttpClient.java, src/test/java/org/folio/services/item/ItemUtilsTest.java, src/test/java/org/folio/services/item/PatchDataTest.java
[MODINVSTOR-1441](https://folio-org.atlassian.net/browse/MODINVSTOR-1441) Create a new API to support the update of items' order.
Implement the `PATCH /item-storage/items` endpoint to support partial updates of items in batches.
Request body field details:
- `id` - required UUID-string field for item identification
- `_version` - required integer field for optimistic locking support
The request could also contain other item schema fields.
The logic of item update:
All the same validations as single item PUT
+ validations of required fields
Instance created with two holdings records, each holdings record has different call number type + call number, 3 items created for 1'st holdings:
Effective values for item2:
PATCH request executed with body changing order of all items + moving item2 to …
=> feat(patch-items-endpoint) Create a new API to support the update of items' order.

ramls/item-storage.raml, src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java, src/main/java/org/folio/rest/support/ItemEffectiveLocationUtil.java, src/main/java/org/folio/services/ItemEffectiveValuesService.java, src/main/java/org/folio/services/item/ItemService.java, src/test/java/org/folio/rest/api/ItemStorageTest.java
[MODINVSTOR-1441](https://folio-org.atlassian.net/browse/MODINVSTOR-1441) fix EffectiveLocationId field and callNumber components
- Fixed the logic for updating Item **`effectiveLocationId`** to correctly handle cases where `temporaryLocationId` and `permanentLocationId` are null in the request body. The `effectiveLocationId` will then be retrieved from the item's associated holding record, using the resolved `temporaryLocationId` and `permanentLocationId`.
When both values (Item `temporaryLocationId` and `permanentLocationId`)  are not present in the request, they are retrieved from the existing item record in the database.
- Fixed the logic for building **CallNumber components**
- Updated the API info: endpoint description and request body example
* **Added API endpoint description:** …
=> fix(patch-items-endpoint) fix EffectiveLocationId field and callNumber components
