folio-org/mod-inventory-storage

- pom.xml
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/api/LoanTypeTest.java
- src/test/java/org/folio/rest/api/MaterialTypeTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/TestBase.java
> extract duplicated code into TestBase.java; enable *Test.java invocation

- Jenkinsfile
- ramls/examples/instances_get.json
- ramls/instances.json
- ramls/items.json
> FOLIO-351 whitespace tidy 1

- src/main/java/org/folio/rest/impl/LoanTypeAPI.java
preparation to replace PostgresClient with a stub for unit tests
> extract duplicated code into getPostgresClient(...)

- pom.xml
Marc, Let me know if you are OK with this change.
> add maven-release plugin to POM

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/item-storage.raml
- ramls/item.json
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/support/JsonObjectMatchers.java
item-storage interface version 4.1
> Make title optional for an item MODINVSTOR-31

- .editorconfig
> Re-introduce * editor config

- NEWS.md
- ramls/location.raml
- sample-data/instances/transparent-water.json
- src/main/java/org/folio/rest/impl/LocationUnitAPI.java
Whitespace.
Remove a license header.
> FOLIO-398 tidy 5

- src/main/java/org/folio/rest/impl/LocationAPI.java
- src/test/java/org/folio/rest/api/LocationUnitTest.java
Trivial tests to try to improve test coverage
> Add a few more tests

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/location.json
- ramls/location.json
- reference-data/locations/deep.json
- reference-data/locations/main-library.json
- src/test/java/org/folio/rest/api/LocationsTest.java
Add "description" and "discoveryDisplayName"
> Modinvstor 113 description

- NEWS.md
> FOLIO-1253 test generate-api-docs 2

- sample-data/instances/bridgets-baby-instance.json
- sample-data/instances/girl-on-the-train-instance.json
- sample-data/instances/interesting-times-instance.json
- sample-data/instances/nod-instance.json
- sample-data/instances/temeraire-instance.json
- sample-data/instances/transparent-water.json
- sample-data/instances/water-resources-of-east-feliciana-parish.json
> Remove "primary" property from contributors sample data.

- NEWS.md
- pom.xml
- quick-test.sh
- src/main/java/org/folio/rest/impl/ItemStorageAPI.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
Resolves [MODINVSTOR-137](https://issues.folio.org/browse/MODINVSTOR-137):
Added default status to Items, 'Available'
> Modinvstor 137

- sample-data/instances/anglo-saxon-manuscripts.json
- sample-data/instances/biometrics-and-neuroscience.json
- sample-data/instances/cantatas-for-bass.json
- sample-data/instances/chess-player.json
- sample-data/instances/city-post-modernity.json
- sample-data/instances/concepts-of-fashion.json
- sample-data/instances/dc-motor-control-experiment.json
- sample-data/instances/journey-through-europe.json
- sample-data/instances/neurotic-heroine.json
- sample-data/instances/signature-of-complex-system.json
> Update instance types in instance sample data.

- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/support/ResponseHandler.java
https://issues.folio.org/browse/MODINVSTOR-157
> Fix incorrect content type warning when creating an item in API tests

- src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java
Resolves [MODINVSTOR-15](https://issues.folio.org/browse/MODINVSTOR-15):
This addresses the vulnerabilities referenced by sonarcloud.
> Modinvstor 15

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/location.json
- ramls/location.raml
- ramls/servicepoint.json
- src/main/java/org/folio/rest/impl/LocationAPI.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/LocationUnitTest.java
- src/test/java/org/folio/rest/api/LocationsTest.java
- src/test/java/org/folio/rest/api/ServicePointTest.java
- src/test/java/org/folio/rest/api/ServicePointsUserTest.java
- src/test/java/org/folio/rest/api/ShelfLocationsTest.java
This includes the code covered by [pr#173](https://github.com/folio-org/mod-inventory-storage/pull/173) for [MODINVSTOR-177](https://issues.folio.org/browse/MODINVSTOR-177)
> Tmp release 13.0.0

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/location.json
- ramls/location.raml
- ramls/servicepoint.json
- src/main/java/org/folio/rest/impl/LocationAPI.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/LocationUnitTest.java
- src/test/java/org/folio/rest/api/LocationsTest.java
- src/test/java/org/folio/rest/api/ServicePointTest.java
- src/test/java/org/folio/rest/api/ServicePointsUserTest.java
- src/test/java/org/folio/rest/api/ShelfLocationsTest.java
This resolves [MODINVSTOR-177](https://issues.folio.org/browse/MODINVSTOR-177):
In this PR I have added a primaryServicePoint property to the Location entity. I have also reversed the relationship of Location to ServicePoint so that Location is now the owner.  There was also the introduction of some composite future tooling to the LocationAPiI to handle running multiple checks during CRUD operations.
> Modinvstor 177 breaking changes

- ramls/examples/location.json
- ramls/examples/servicepoint.json
With this PR the examples now accurately reflect the state of Location and ServicePoint as of 13.0.0
> Corrected location and servicepoint examples

- src/main/resources/templates/db_scripts/schema.json
Seems to improve perfomance on filtering by the type.
> Use fulltext indexing for instanceType

- ramls/instance.json
Finished instance.json only.
Move some descriptions up to the encompassing property.
Add remaining missing descriptions.
Tidy.
> MODINSTOR-179 schema descriptions

- ramls/classificationtype.json
- ramls/classificationtypes.json
- ramls/contributornametype.json
- ramls/contributornametypes.json
- ramls/contributortype.json
- ramls/contributortypes.json
- ramls/holdingsrecord.json
- ramls/holdingsrecords.json
- ramls/identifiertype.json
- ramls/identifiertypes.json
- ramls/instance.json
- ramls/instances.json
- ramls/item.json
- ramls/items.json
- ramls/loantype.json
- ramls/loantypes.json
- ramls/materialtype.json
- ramls/materialtypes.json
- ramls/platform.json
- ramls/platforms.json
- ramls/servicepoint.json
- ramls/servicepoints.json
- ramls/servicepointsuser.json
- ramls/servicepointsusers.json
- ramls/statisticalcodetype.json
- ramls/statisticalcodetypes.json
> MODINVSTOR-203 schema descriptions 1

- pom.xml
RMB v23.1.0 now closes SQL connection
> MODINVSTOR-214: Update to RMB v23.1.0, fix hang issue

- src/main/resources/templates/db_scripts/holdingsRecordHrid.sql
- src/main/resources/templates/db_scripts/instanceHrid.sql
- src/main/resources/templates/db_scripts/itemHrid.sql
> MODINVSTOR-253: ERROR: sequence must be in same schema as table it is linked to

- src/main/java/org/folio/rest/impl/InstanceNoteTypeAPI.java
> Remove redundant call

- src/main/resources/templates/db_scripts/schema.json
The barcode related SQL changed with recent RMB release. Adjust the index build to match that.
> Match barcode index with SQL generated

- src/main/java/org/folio/rest/impl/InstanceStorageAPI.java
Follow up issue resolved MODINVSTOR-331
> Modinvstor 319

- descriptors/ModuleDescriptor-template.json
- ramls/examples/instance_get.json
- ramls/examples/instance_post.json
- ramls/examples/instances_get.json
- ramls/instance-storage-batch.raml
- ramls/instance-storage.raml
- ramls/instance.json
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
Due to https://issues.folio.org/browse/MODINV-135 we would like to introduce tags for instance entities.  
* updated instance model with tags
* updated instance interfaces versions
> MODINVSTOR-323 - Inventory App: Assign tags to instance record

- descriptors/ModuleDescriptor-template.json
- ramls/examples/item_get.json
- ramls/examples/item_post.json
- ramls/item-storage.raml
- ramls/item.json
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java
Due to https://issues.folio.org/browse/MODINVSTOR-322 we would like to introduce tags for item entities.
* updated item model with tags
* updated item interfaces versions
> MODINVSTOR-322 Inventory App: Assign tags to item record

- descriptors/ModuleDescriptor-template.json
- ramls/instance-storage.raml
- ramls/instance.json
- sample-data/instances/aba.json
- sample-data/instances/american-journal-of-medicine.json
- sample-data/instances/girl-on-the-train.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- Add natureOfContentTermIds to Instance domain
- Update sample data
- Create test-case
> MODINVSTOR-327, UIIN-470: Add natureOfContentTermIds field to Instance.

- pom.xml
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/SampleDataTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
* Update to RMB 27, use targetPath foreign key syntax
* add sample data unit test
Before merging change RMB version to 27!
> MODINVSTOR-342: Update to RMB 27

- pom.xml
So annoying that I always have to clean to make tests work
> Fix Aspect issue (mvn clean; mvn test; mvn test)

- reference-data/instance-relationship-types/preceding-succeeding.json
- sample-data/instance-relationships/american-bar-association-preceding-title.json
- sample-data/instances/american-bar-association.json
- src/test/java/org/folio/rest/api/ReferenceTablesTest.java
- src/test/java/org/folio/rest/api/SampleDataTest.java
* Add preceding-succeeding relationship type
* Add tests 
* Add sample data
> MODINVSTOR-343: Add preceding-succeeding relationship. Add sample data.

- reference-data/alternative-title-types/UniformTitle.json
- src/test/java/org/folio/rest/api/ReferenceTablesTest.java
* Add new alternative title type
* Modify test
> MODINVSTOR-350: Add uniform alternative title type.

- ramls/shelf-location.raml
- ramls/shelflocation.json
- ramls/shelflocations.json
> MODINVSTOR-203: Add description for shelflocation.json

- ramls/holdingsrecord.json
> corrected wording in holdingsrecord.json

- src/main/resources/templates/db_scripts/schema.json
This option is not documented and does not work.
> MODINVSTOR-377: Remove fullText / defaultDictionary option

- src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java
> MODINVSTOR-393: Add where claus for holdings record update statement.

- src/main/resources/templates/db_scripts/schema.json
Add foreign key constraint and remove existing btree index on effective location. See comments of [MODINVSTOR-407](https://issues.folio.org/browse/MODINVSTOR-407?focusedCommentId=66781&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-66781).
> MODINVSTOR-407 Add foreign key constraint for effective location

- reference-data/modes-of-issuance/integratingresource.json
- reference-data/modes-of-issuance/multipartmonograph.json
- reference-data/modes-of-issuance/serial.json
- reference-data/modes-of-issuance/singleunit.json
- reference-data/modes-of-issuance/unspecified.json
- src/main/resources/templates/db_scripts/renameModesOfIssuance.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/ModesOfIssuanceMigrationScriptTest.java
- src/test/java/org/folio/rest/api/TestBase.java
- src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-431
- rename modes of issuance
- create migration script
> MODINVSTOR-431 Settings > Inventory > Mode of issuance. Misc. renaming and source update of existing values

- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/support/builders/ItemRequestBuilder.java
- src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-444 - add indexes for call number searching (eye readable).
Add indexes:
* fullCallNumber = prefix + callNumber + suffix
* callNumberAndSuffix = callNumber + suffix
* fullCallNumber = effectiveCNC.prefix + effectiveCNC.callNumber + effectiveCNC.suffix
* callNumberAndSuffix = effectiveCNC.callNumber + effectiveCNC.suffix
> MODINVSTOR-444: Add indexes for item and holdings call number.

- descriptors/ModuleDescriptor-template.json
- ramls/examples/precedingsucceedingtitle_get.json
- ramls/examples/precedingsucceedingtitles_get.json
- ramls/instance-preceding-succeeding-titles.raml
- ramls/instanceprecedingsucceedingtitle.json
- ramls/instanceprecedingsucceedingtitles.json
- src/main/java/org/folio/rest/impl/PrecedingSucceedingTitleAPI.java
- src/main/resources/templates/db_scripts/alterPrecedingSucceedingTitle.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/PrecedingSucceedingTitleTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/TestBase.java
- src/test/java/org/folio/rest/api/entities/PrecedingSucceedingTitle.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
- src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-441
Create new table for preceding/succeeding titles
Create new crud endpoints for preceding/succeeding titles
> MODINVSTOR-441 Preceding titles ability to add "unconnected" and "connected" title (create, edit)

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/holdings-storage.raml
- ramls/holdingsrecords.json
- ramls/instance-storage.raml
- ramls/instances.json
- ramls/item-storage.raml
- ramls/items.json
- src/main/java/org/folio/rest/impl/HoldingsStorageAPI.java
- src/main/java/org/folio/rest/impl/InstanceStorageAPI.java
- src/main/java/org/folio/rest/impl/ItemStorageAPI.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
Note: using snapshot of RMB which is not even released.
The /instance-storage/instances is problematic and is not using
the "optimized" version no more. Better make an RMB change for that
rather than trying to fix it here.
> PgUtil.streamGet for instances, holdings, items storage MODINVSTOR-438

- descriptors/ModuleDescriptor-template.json
- ramls/holdings-storage.raml
- ramls/holdingsrecord.json
Needed for ReShare issue PR-611.
> Add `illPolicy` link-field annotation for mod-graphql

- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
- src/test/java/org/folio/rest/support/builders/JsonRequestBuilder.java
https://issues.folio.org/browse/MODINVSTOR-473 - Add b-tree indexes for staffSuppress and discoverySuppress properties
> MODINVSTOR-473: [RELEASE] Add b-tree indexes for staffSuppress and discoverySuppress properties

- src/main/resources/templates/db_scripts/oaipmh/createOaiPmhViewFunction.sql
- src/main/resources/templates/db_scripts/oaipmh/revert_createOaiPmhViewFunction.sql
- src/main/resources/templates/db_scripts/schema.json
Since OAI-PMH response is going to be expanded with some holdings and items field, database view should be created in Inventory to retrieve this data in a more convenient way.
> MODINVSTOR-486: Create view in Inventory for OAI-PMH

- pom.xml
MODINVSTOR-525: Release mod-inventory-storage 19.2.3
> MODINVSTOR-525: Release mod-inventory-storage 19.2.3

- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-480 - Holdings record. Call number, eye readable. Search on exact data in Call number data element
Add tests to verify jira scenarios can be done with the chosen approach.
> MODINVSTOR-480: Add tests for eye readable call number search.

- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/ItemStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-481 - Item record. Effective call number (item), eye readable. Search on exact data in Call number data element.
* Add b-tree index for `effectiveCallNumberComponents.callNumber`;
* Add tests to verify jira scenarios.
> MODINVSTOR-48: Add index for item effective call number.

- pom.xml
Version of mainline development branch has been prared for further updates.
> Updating of version after issuing of release 19.3.0.

- NEWS.md
- pom.xml
Upgrade from RMB 30.2.4 to 30.2.6. For details see NEWS.md.
> MODINVSTOR-559: Release 19.3.2

- src/main/resources/templates/db_scripts/inventory-hierarchy/createRecordsViewFunction.sql
Fixed issues found after merging MODINVSTOR-518: Transform OAI-PMH view API in Inventory into general API
> MODINVSTOR-570: Issues in /inventory-hierarchy enpoints

- src/main/resources/templates/db_scripts/schema.json
Fix createRecordsViewFunction version in schema.json
Jira: https://issues.folio.org/browse/MODINVSTOR-570
> Fix createRecordsViewFunction version in schema.json

- ramls/service-points-user.raml
- src/main/java/org/folio/rest/impl/ServicePointsUserAPI.java
- src/test/java/org/folio/rest/api/ServicePointsUserTest.java
https://issues.folio.org/browse/MODINVSTOR-573 - Unable to upgrade inventory-storage on rancher env
> MODINVSTOR-573: Return 422 when service point user does not exist.

- reference-data/ill-policies/WillNotLend.json
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/updateIllPolicyWillNotLend.sql
- src/test/java/org/folio/rest/api/IllMigrationScriptTest.java
- src/test/java/org/folio/rest/api/TestBase.java
- src/test/java/org/folio/rest/api/illMigrationScriptTest.java
- src/test/java/org/folio/rest/support/http/ResourceClient.java
Resolves https://issues.folio.org/browse/MODINV-314
> capitalize WillNotLend ill reference data

- src/main/java/org/folio/rest/impl/InventoryHierarchyAPI.java
Fix timeout on initial oai-pmh repository load (both empty until & from).
> MODOAIPMH-237: Timeout on the initial load

- NEWS.md
- pom.xml
- ramls/service-points-user.raml
- src/main/java/org/folio/rest/impl/ServicePointsUserAPI.java
- src/test/java/org/folio/rest/api/ServicePointsUserTest.java
Includes https://github.com/folio-org/mod-inventory-storage/pull/508
> Release mod-inventory-storage v19.3.6

- NEWS.md
- pom.xml
* Upgrade to RMB 31.1.5 (MODINVSTOR-611)
> MODINVSTOR-612: Release 19.4.2

- src/main/resources/templates/db_scripts/schema.json
1. New "GIN-index" added for the "electronicAccess" field.
> MODINVSTOR-610: Data import with 856 --> electronicAccess match performance issues.

- descriptors/ModuleDescriptor-template.json
- ramls/item-storage.raml
- ramls/item.json
- src/test/java/org/folio/rest/api/ItemStorageTest.java
> MODINVSTOR-615 : States has been added and sorted

- NEWS.md
- ramls/holdingsrecordssource.json
I inserted the source line as requested.
refs: https://issues.folio.org/browse/MODINVSTOR-619
> MODINVSTOR-619: source property missing type property

- pom.xml
- src/main/java/org/folio/rest/impl/AbstractInstanceRecordsAPI.java
Followup to https://issues.folio.org/browse/RMB-776
> Update to Vert.x 4.0.0 final

- src/test/java/org/folio/rest/api/StorageTestSuite.java
See FOLIO-2908. Purge and other operations are now handled
almost same way so code refactored a bit.
> Handle both 201 and 204 for tenant operation MODINVSTOR-648

- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/test/java/org/folio/rest/api/KafkaTenantInitTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
https://issues.folio.org/browse/MODINVSTOR-655 - Do not call create topics service when tenantInit.purge==true
> MODINVSTOR-655: Do not create topics when tenant is being purged.

- src/main/resources/templates/db_scripts/schema.json
Please see https://issues.folio.org/browse/MODINVSTOR-627
> MODINVSTOR-627: add allTitles index

- src/main/java/org/folio/persist/AbstractRepository.java
- src/main/java/org/folio/rest/impl/InstanceStorageAPI.java
- src/main/java/org/folio/rest/persist/PostgresClientFuturized.java
- src/main/java/org/folio/services/domainevent/AbstractDomainEventPublisher.java
- src/main/java/org/folio/services/holding/HoldingsService.java
- src/main/java/org/folio/services/item/ItemService.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java
- src/test/java/org/folio/rest/support/matchers/DomainEventAssertions.java
https://issues.folio.org/browse/MODINVSTOR-662 - When instance/item/holding created send record from DB as domain event
> MODINVSTOR-662: Publish instance/item/holdings from DB

- NEWS.md
- reference-data/identifier-types/CancelledSystemControlNumber.json
- src/main/resources/templates/db_scripts/addIdentifierTypeCancelledSystemControlNumber.sql
- src/main/resources/templates/db_scripts/schema.json
"Cancelled system control number"
> Add identifier type to reference data (MODINVSTOR-636)

- pom.xml
- ramls/item.json
- src/main/java/org/folio/rest/impl/ItemStorageAPI.java
- src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java
- src/main/java/org/folio/services/CallNumberUtils.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/services/CallNumberUtilsTest.java
> MODINVSTOR-381

- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/examples/inventory-view-instances.json
- ramls/inventory-view-instance.json
- ramls/inventory-view.raml
- src/main/java/org/folio/rest/impl/InventoryViewAPI.java
- src/main/resources/templates/db_scripts/instance-hr-item/instance-hr-item-view.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InventoryViewTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/TestBase.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
- src/test/java/org/folio/rest/support/http/ResourceClient.java
https://issues.folio.org/browse/MODINVSTOR-674 - Implement bulk instance endpoint
* Implement `inventory-view` API;
* Register new `instance_holdings_item_view` view.
> MODINVSTOR-674: Implement inventory view instances API

- pom.xml
As changes since last release include implementation breaking changes
> Update version to 20.0.0 MODINVSTOR-666

- src/main/resources/templates/db_scripts/schema.json
Please see https://issues.folio.org/browse/RMB-797
> Add contributorsNames index

- NEWS.md
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
I added code for the new index, modeling it on similar indexes that already 
exist in the instances table.  As requested, I removed the gindex for this field.
> MODINVSTOR-716: Query search on classifications times out.

- NEWS.md
- pom.xml
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/rest/support/EffectiveCallNumberComponentsUtil.java
- src/main/java/org/folio/services/item/ItemService.java
- src/main/java/org/folio/services/migration/BaseMigrationService.java
- src/main/java/org/folio/services/migration/BatchedReadStream.java
- src/main/java/org/folio/services/migration/item/ItemShelvingOrderMigrationService.java
- src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java
- src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/services/migration/BatchedReadStreamTest.java
- src/test/java/org/folio/services/migration/item/ItemShelvingOrderMigrationServiceTest.java
Releases: https://github.com/folio-org/mod-inventory-storage/pull/609
> Release mod-inventory-storage 20.2.0

- src/main/java/org/folio/persist/AbstractRepository.java
- src/main/java/org/folio/services/migration/item/ItemShelvingOrderMigrationService.java
- src/test/java/org/folio/services/migration/item/ItemShelvingOrderMigrationServiceTest.java
Back port from https://github.com/folio-org/mod-inventory-storage/pull/615
> MODINVSTOR-521: Do not send domain events for item shelving order migration

- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/services/instance/InstanceEffectiveValuesService.java
- src/main/java/org/folio/services/instance/InstanceService.java
- src/main/java/org/folio/services/instance/PublicationPeriodParser.java
- src/main/java/org/folio/services/migration/BaseMigrationService.java
- src/main/java/org/folio/services/migration/instance/PublicationPeriodMigrationService.java
- src/main/java/org/folio/services/migration/item/ItemShelvingOrderMigrationService.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java
- src/test/java/org/folio/rest/api/PublicationPeriodMigrationServiceApiTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/services/domainevent/LogToDbFailureHandlerTest.java
- src/test/java/org/folio/services/instance/InstanceEffectiveValuesServiceTest.java
- src/test/java/org/folio/services/instance/PublicationPeriodParserTest.java
* Implement dateOfPublication parsing logic as per requirements;
* Populate the publicationPeriod on instance create/update if the dateOfPublication changed and the period is not set yet;
* Move stream processing logic for java migrations to base class.
* Add java migration for the new property.
> MODINVSTOR-724: Populate publication period property for instance.

- descriptors/ModuleDescriptor-template.json
- ramls/instance-preceding-succeeding-titles.raml
- ramls/instance-storage.raml
- src/main/java/org/folio/rest/impl/InstanceStorageAPI.java
- src/main/java/org/folio/rest/impl/PrecedingSucceedingTitleAPI.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/PrecedingSucceedingTitleTest.java
- src/test/java/org/folio/rest/api/entities/PrecedingSucceedingTitles.java
Add PUT title collection endpoint
* extend `instance-preceding-succeeding-titles` API with new endpoint
* add tests
> MODINVSTOR-742 Add PUT title collection endpoint

- src/main/java/org/folio/rest/impl/ServicePointAPI.java
Replace code by PgUtil.get.
The code has been written before PgUtil.get.
> MODINVSTOR-761: Return 400, not 500, for service-points invalid CQL

- NEWS.md
- src/main/resources/templates/db_scripts/schema.json
As this change wasn't included in the 20.2.0 release (which was made from a divergent branch)
For more information, please refer to https://issues.folio.org/browse/MODINVSTOR-759?focusedCommentId=109699&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-109699
> Apply changes to items and holdings view from version 20.3.0 MODINVSTOR-759

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InventoryHierarchyViewTest.java
- src/test/java/org/folio/rest/api/InventoryViewTest.java
- src/test/java/org/folio/rest/api/ItemEffectiveCallNumberComponentsTest.java
- src/test/java/org/folio/rest/api/ItemShelvingOrderMigrationServiceApiTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/api/OaiPmhViewTest.java
- src/test/java/org/folio/rest/support/builders/ItemRequestBuilder.java
- src/test/java/org/folio/rest/support/matchers/ResponseMatcher.java
This backports "Enforce item barcode uniqueness" ([MODINVSTOR-523](https://issues.folio.org/browse/MODINVSTOR-523)) = #648 from master to b21.0 for Juniper (R2 2021) Hot Fix # 2
> Release 21.0.4

- NEWS.md
- reference-data/identifier-types/ISMN.json
- reference-data/identifier-types/InvalidIsmn.json
- reference-data/identifier-types/InvalidUpc.json
- reference-data/identifier-types/UPC.json
- src/main/resources/templates/db_scripts/addIdentifierTypesUpcIsmn.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/UpcIsmnMigrationScriptTest.java
I added reference files, a migration script, and a test for the migration script.
> MODINVSTOR-770: Add new values: Invalid ISMN, Invalid UPC, ISMN and UPC

- NEWS.md
- pom.xml
Most notable fix in RMB 33.1.1: Database memory issue https://issues.folio.org/browse/RMB-863
> MODINVSTOR-793: Update RMB to 33.1.1 and Vert.x to 4.1.4

- src/main/resources/templates/db_scripts/populatePublicationPeriod.sql
- src/main/resources/templates/db_scripts/schema.json
Keep populatePublicationPeriod.sql for manual execution.
> MODINVSTOR-774: Disable automatic publicationPeriod migration

- src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java
- src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
Note:
This pull request is intended to be merged into the other pull request kafka-topics-insert-always.
> createTopics as loop

- pom.xml
- src/main/java/org/folio/services/kafka/topic/KafkaAdminClientService.java
- src/test/java/org/folio/rest/api/KafkaTopicsExistsTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/services/kafka/topic/KafkaAdminClientServiceTest.java
- src/test/java/org/folio/services/kafka/topic/KafkaTopicsExistsTest.java
Create topics always and ignore if topic already exists, thus having
the effect of "create if not exists".
> Create topics always MODINVSTOR-839

- ramls/authorities/authority.json
Rename 'hGenreTerm' to 'genreTerm'
> MODINVSTOR-850 Rename 'hGenreTerm' to 'genreTerm'

- src/main/java/org/folio/rest/impl/RecordBulkAPI.java
- src/test/java/org/folio/rest/api/RecordBulkTest.java
[MODINVSTOR-872](https://issues.folio.org/browse/MODINVSTOR-872) - Improve record-bulk/ids endpoint to support effective location included in the cql
* Improved endpoint logic
* Updated unit tests
> MODINVSTOR-872 - Improve record-bulk/ids endpoint to support effective location included in the cql

- src/main/java/org/folio/rest/impl/InitApiImpl.java
- src/main/java/org/folio/rest/impl/TenantRefAPI.java
- src/main/java/org/folio/services/kafka/KafkaProperties.java
- src/main/java/org/folio/services/kafka/topic/KafkaTopic.java
- src/main/java/org/folio/services/migration/async/AsyncMigrationConsumerVerticle.java
- src/main/java/org/folio/services/migration/async/AsyncMigrationsConsumerUtils.java
- src/main/java/org/folio/services/migration/async/PublicationPeriodMigrationJobRunner.java
fix subscription for async migration consumer
> MODINVSTOR-862 Implement non-blocking Java migration for publicationPeriod as a separate process

- ramls/examples/relatedinstance.json
- ramls/examples/relatedinstances.json
- ramls/relatedinstance.json
- src/main/java/org/folio/services/relatedInstance/RelatedInstanceService.java
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/RelatedInstanceTest.java
Resolves https://issues.folio.org/browse/MODINVSTOR-898
> [MODINVSTOR-898] refactor related instance type id

- src/main/java/org/folio/rest/persist/PostgresClientFuturized.java
Use a Future returning method from PostgresClient if available to avoid creating a Promise.
> MODINVSTOR-903: Avoid Promise in PostgresClientFuturized

- src/main/resources/templates/db_scripts/inventory-hierarchy/correctGetUpdatedInstanceIdsView.sql
> MODINVSTOR-912 - Update SQL

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/inventory-hierarchy/correctGetUpdatedInstanceIdsView.sql
[MODINVSTOR-919](https://issues.folio.org/browse/MODINVSTOR-919) - Release 23.0.4
> MODINVSTOR-919 - Release 23.0.4

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-920](https://issues.folio.org/browse/MODINVSTOR-920) - MODINVSTOR (mod-inventory-storage) Lotus HF#1
- Increase DB script fromModuleVersion to 23.0.5
> Release 23.0.5 MODINVSTOR-920

- src/main/java/org/folio/services/reindex/ReindexService.java
- src/test/java/org/folio/services/reindex/ReindexServiceTest.java
https://issues.folio.org/browse/MODINVSTOR-936
> MODINVSTOR-936 Restrict cancelation of already finished reindex job

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/examples/instance-set.json
- ramls/instance-set.json
- ramls/instance-set.raml
- ramls/instance-sets.json
- src/main/java/org/folio/persist/InstanceRepository.java
- src/main/java/org/folio/rest/impl/InstanceSetAPI.java
- src/main/java/org/folio/rest/support/EndpointHandler.java
- src/main/java/org/folio/services/instance/InstanceService.java
- src/main/resources/templates/db_scripts/createInstanceSetView.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InstanceRelationshipsTest.java
- src/test/java/org/folio/rest/api/InstanceSetTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/support/http/InterfaceUrls.java
The implementation should be as general as possible and easy to extend
so that it can be used for many use cases.
> MODINVSTOR-918: GET Instance Set by CQL

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/schema.json
I asked for review on this because I've never released an operator script before.  My understanding from talking
to others is that we put the script in the wiki, and refer to it in the release notes.  I've put information about it in the newsfile here to be used in the release notes.
> MODINVSTOR-940: back port to 24.0.2

- src/main/java/org/folio/services/CallNumberUtils.java
- src/test/java/org/folio/services/CallNumberUtilsTest.java
https://issues.folio.org/browse/MODINVSTOR-942
> MODINVSTOR-942 Revert shelfKey pattern check for call-number

- Jenkinsfile
- pom.xml
- src/test/java/org/folio/rest/InstallUpgradeIT.java
- src/test/resources/lotus-23.0.0.sql
Add an InstallUpgradeIT.java integration test. It should check the shaded fat uber jar and Dockerfile:
* Test /admin/health.
* Test that logging works.
* Test installation and migration with smoke test.
> MODINVSTOR-927: InstallUpgradeIT

- NEWS.md
- README.MD
- pom.xml
- src/main/java/org/folio/services/CallNumberUtils.java
- src/main/java/org/folio/services/reindex/ReindexService.java
- src/test/java/org/folio/services/CallNumberUtilsTest.java
- src/test/java/org/folio/services/reindex/ReindexServiceTest.java
Include release 24.0.3 to branch 24.0
This PR contains changes from 24.0.3 release: [Git comparing](https://github.com/folio-org/mod-inventory-storage/compare/v24.0.2...v24.0.3).
> MODINVSTOR-946 release 24.0.3 

- ramls/hridsettings.json
- src/main/resources/templates/db_scripts/schema.json
Jira: https://issues.folio.org/browse/MODINVSTOR-956
> [MODINVSTOR-956] Add metadata to hrid settings

- descriptors/ModuleDescriptor-template.json
- ramls/service-point.raml
- ramls/servicepoint.json
- ramls/time-period.json
- src/test/java/org/folio/rest/api/ServicePointTest.java
[MODINVSTOR-599] ( https://issues.folio.org/browse/MODINVSTOR-599 )
- Create enum for persisting settings of Closed Library Date Management in Service Point object 
- updated raml of HoldShelfExpiryPeriod 
- test case updated where HoldShelfExpiryPeriod is accepted in api
> Modinvstor 599

- src/test/java/org/folio/rest/api/AbstractInstanceRecordsAPITest.java
Rather than awaitility and exception catching
> Use mockito timeout when checking for http responses MODINVSTOR-1001

- ramls/bound-with-part.raml
- ramls/boundWith.json
- ramls/boundWiths.json
- ramls/examples/boundWiths.json
> Remove obsolete type, example; incl. good example (MODINVSTOR-1022)

- pom.xml
Updated folio-kafka-wrapper to 2.7.0
> [KAFKAWRAP-33] Updated folio-kafka-wrapper to 2.7.0

- src/main/java/org/folio/services/holding/HoldingsService.java
- src/main/java/org/folio/services/instance/InstanceService.java
- src/main/java/org/folio/services/item/ItemService.java
- src/main/java/org/folio/validator/NotesValidators.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
- src/test/java/org/folio/rest/api/InstanceStorageTest.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
- src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
Limited Instance/Holdings/Item/administrative notes and notes maximum length
> MODINVSTOR-1005 Limit Instance/Holdings/Item/administrative notes maximum length 

- src/main/java/org/folio/rest/impl/InventoryHierarchyAPI.java
- src/main/resources/templates/db_scripts/inventory-hierarchy/updateRecordsViewFunctionToSupportSourceFix.sql
- src/main/resources/templates/db_scripts/inventory-hierarchy/updateRecordsViewFunctionToSupportSourceImprove.sql
- src/main/resources/templates/db_scripts/schema.json
Follow-up commit to [PR#890](https://github.com/folio-org/mod-inventory-storage/pull/890) with updating query logic - taking into account instances audit filtration.
> MODINVSTOR-1045 - Supporting source in /inventory-hierarchy/updated-instance-ids (query updating)

- src/main/java/org/folio/rest/impl/CallNumberTypeAPI.java
- src/main/java/org/folio/rest/support/EndpointFailureHandler.java
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/updateCallNumberSource.sql
- src/test/java/org/folio/rest/api/ReferenceTablesTest.java
- src/test/java/org/folio/rest/api/StorageTestSuite.java
- src/test/java/org/folio/rest/api/TestBase.java
- src/test/java/org/folio/rest/impl/CallNumberTypeAPITest.java
Add concept of system call number type to make them not editable, not deletable
- update 5 call-numbers types from reference data to have source 'system' 
- update API implementation to use PgUtil
- add checks in API implementation, that restricts to delete or update system call number type
> MODINVSTOR-1046 Add concept of system call number type

- reference-data/call-number-types/DeweyDecimalClassification.json
- reference-data/call-number-types/LibraryOfCongressClassification.json
- reference-data/call-number-types/NationalLibraryOfMedicineClassification.json
- reference-data/call-number-types/OtherScheme.json
- reference-data/call-number-types/SuperIntendentOfDocumentsClassification.json
update source to system for call-number-types in reference data
> MODINVSTOR-1046 update source to system in reference data

- src/main/java/org/folio/rest/support/EndpointFailureHandler.java
- src/main/java/org/folio/services/item/ItemService.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
Unified validation error handling. Also ResponseException handling moved to EndpointFailureHandler
> MODINVSTOR-1055 Unify API response in case of ValidationException (http 422)

- src/test/java/org/folio/rest/api/AsyncMigrationTest.java
Fix timeout in AsyncMigrationTest.canMigrateInstanceSubjectsAndSeries
Add additional await() for updating a record
> MODINVSTOR-1047 Fix timeout in AsyncMigrationTest.canMigrateInstanceSubjectsAndSeries

- src/main/java/org/folio/services/item/ItemService.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
Fix metadata update on call number changed via holdings record
Added metadata update function
[MODINVSTOR-1053](https://issues.folio.org/browse/MODINVSTOR-1053)
> MODINVSTOR-1053: Fix of metadata update on call number changes via the holdings record

- descriptors/ModuleDescriptor-template.json
- ramls/authorities-reindex.raml
- ramls/examples/reindexJob.json
- ramls/examples/reindexJobs.json
- ramls/instance-reindex.raml
- ramls/reindex/reindex-jobs.json
- src/main/java/org/folio/rest/impl/ReindexAuthoritiesApi.java
- src/main/java/org/folio/rest/impl/ReindexInstanceApi.java
- src/test/java/org/folio/rest/api/ReindexJobRunnerTest.java
- src/test/java/org/folio/rest/support/fixtures/AuthorityReindexFixture.java
- src/test/java/org/folio/rest/support/fixtures/InstanceReindexFixture.java
feat(reindex): Create endpoints to retrieve all reindex jobs
Create endpoint GET /instance-storage/reindex
Create endpoint GET /authority-storage/reindex
Closes: MODINVSTOR-990
> MODINVSTOR-990 Create endpoints to retrieve all reindex jobs

- src/main/java/org/folio/services/item/ItemService.java
- src/test/java/org/folio/rest/api/HoldingsStorageTest.java
Make metadata updatedByUserId field's value available
_updatedByUserId_ field value is set in metadata creation method.
[MODINVSTOR-1063](https://issues.folio.org/browse/MODINVSTOR-1063)
> MODINVSTOR-1063: Metadata field updatedByUserId added in metadata creation

- descriptors/ModuleDescriptor-template.json
feat(reindex): Create endpoints to retrieve all reindex jobs
- Updated permissions for new endpoints
Closes: MODINVSTOR-990
> MODINVSTOR-990 Updated permissions for new endpoints

- .github/workflows/mac.yml
- Dockerfile
- Jenkinsfile
- pom.xml
Migrate to Java version 17
Update Java version and some dependencies/configurations
[MODINVSTOR-1079](https://issues.folio.org/browse/MODINVSTOR-1079)
> MODINVSTOR-1079: Migrate to Java 17

- src/main/java/org/folio/rest/impl/ServicePointApi.java
- src/main/java/org/folio/services/domainevent/ServicePointDomainEventPublisher.java
- src/main/java/org/folio/services/servicepoint/ServicePointService.java
- src/test/java/org/folio/rest/api/ServicePointTest.java
- src/test/java/org/folio/rest/support/messages/ServicePointEventMessageChecks.java
Publish a domain event whenever a service point is deleted.
Resolves [MODINVSTOR-1077](https://issues.folio.org/browse/MODINVSTOR-1077).
> MODINVSTOR-1077: Publish domain event upon service point deletion

- src/main/resources/templates/db_scripts/oaipmh/updateCompleteUpdatedDateForItemInsertUpdateToHandleBoundWith.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/OaiPmhTriggersTest.java
[MODINVSTOR-1070](https://issues.folio.org/browse/MODINVSTOR-1070) - Handle bound-with items
> MODINVSTOR-1070 - Handle bound-with items

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/item.json
- src/test/java/org/folio/rest/api/ItemStorageTest.java
https://issues.folio.org/browse/MODINVSTOR-1154
added new field to item schema
> [MODINVSTOR-1154] - Add new field "Display summary" for the item schema

- src/main/resources/templates/db_scripts/schema.json
Remove left Authority DB tables(**authority**, **authority_note_type** and **authority_source_file**)
Add **mode** field with value **delete** value in schema.json for each table.
> refactor(authorities-tables): delete authorities tables.

- NEWS.md
- pom.xml
- src/test/java/org/folio/rest/impl/AlternativeTitleTypesIT.java
- src/test/java/org/folio/rest/impl/BaseIntegrationTest.java
- src/test/java/org/folio/rest/impl/BaseReferenceDataIntegrationTest.java
Create base for reference data APIs integration tests
- Create base class for integration testing
- Create base class for reference data APIs testing
- Prepare tests for alternative-title-types API
https://folio-org.atlassian.net/browse/MODINVSTOR-1164
> test: create base for reference data APIs integration tests

- NEWS.md
- pom.xml
- src/test/java/org/folio/rest/api/ItemStorageTest.java
Fix unintended update of instance records \_version (optimistic locking) whenever any of its holdings or items are created, updated or deleted.
- Upgrade RMB from Orchid `35.0.4` to Poppy `35.1.3`
- Follow RMB Poppy upgrading guide: https://github.com/folio-org/raml-module-builder/blob/v35.1.3/doc/upgrading.md#version-351
- Poppy version of RMB requires Vert.x 4.4 and Log4j 2.20.
- Therefore upgrade `Vert.x` from Orchid `4.3.5` to Poppy `4.4.9` fixing CVE-2024-1023: https://github.com/advisories/GHSA-5667-3wch-7q7w
- Therefore upgrade `Log4j` from Orchid 2.17.2 to Poppy `2.20.0`.
- Add unit test that checks that the instance \_version no longer changes when changing holding or item.
https://folio-org.atlassian.net/browse/MODINVSTOR-1186
mod-inventory-storage should have been upgraded to …
> MODINVSTOR-1186: RMB 35.1.3 fixing unintended optimistic locking

- src/main/resources/templates/db_scripts/oaipmh/createIndexCompleteUpdatedDate.sql
- src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-1190](https://folio-org.atlassian.net/browse/MODINVSTOR-1190) - Poppy to Quesnelia schema comparison for mod-inventory-storage Poppy to Quesnelia comparison
Add index for oai-pmh completeUpdatedDate.
Update migration script.
> MODINVSTOR-1190 - Poppy to Quesnelia schema comparison for mod-inventory-storage Poppy to Quesnelia comparison

- NEWS.md
- reference-data/identifier-types/CanceledLCCN.json
- src/main/resources/templates/db_scripts/schema.json
- src/main/resources/templates/db_scripts/updateIdentifierTypeCanceledLCCN.sql
change Cancelled LCCN to Canceled LCCN
https://folio-org.atlassian.net/browse/MODINVSTOR-1212
> fix(identifier-types): change Cancelled LCCN to Canceled LCCN

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- ramls/examples/instance-date-types/instanceDateTypePatch.json
- ramls/examples/instance-date-types/instanceDateTypes.json
- ramls/instance-date-type.raml
- ramls/instance-date-types/instanceDateType.json
- ramls/instance-date-types/instanceDateTypePatch.json
- ramls/instance-date-types/instanceDateTypes.json
- reference-data/instance-date-types/continuing-resource-ceased-publication.json
- reference-data/instance-date-types/continuing-resource-currently-published.json
- reference-data/instance-date-types/continuing-resource-status-unknown.json
- reference-data/instance-date-types/date-of-distribution.json
- reference-data/instance-date-types/dates-unknown.json
- reference-data/instance-date-types/detailed-date.json
- reference-data/instance-date-types/inclusive-dates-of-collection.json
- reference-data/instance-date-types/multiple-dates.json
- reference-data/instance-date-types/no-attempt-to-code.json
- reference-data/instance-date-types/no-dates.json
- reference-data/instance-date-types/publication-date.json
- reference-data/instance-date-types/questionable-date.json
- reference-data/instance-date-types/range-of-years-of-bulk-of-collection.json
- reference-data/instance-date-types/reissue-date.json
- reference-data/instance-date-types/single-known-date.json
- src/main/java/org/folio/persist/InstanceDateTypeRepository.java
- src/main/java/org/folio/rest/impl/InstanceDateTypeApi.java
- src/main/java/org/folio/services/instance/InstanceDateTypeService.java
- src/main/resources/templates/db_scripts/addInstanceDateTypes.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/impl/BaseIntegrationTest.java
- src/test/java/org/folio/rest/impl/InstanceDateTypesIT.java
Implement instance-date-types endpoint
- define endpoint
- prepare script to populate default records
https://folio-org.atlassian.net/browse/MODINVSTOR-1235
> feat(instance-date-types): implement instance-date-types endpoint

- reference-data/instance-date-types/continuing-resource-status-unknown.json
- src/main/resources/templates/db_scripts/addInstanceDateTypes.sql
Change code from "e" to "u" for "Continuing resource status unknown"
- Fix reference data json
- Fix sql script
[MODINVSTOR-1239](https://folio-org.atlassian.net/browse/MODINVSTOR-1239)
> fix(instance-date-types) Fix code for "Continuing resource status unknown"

- ramls/reindex-records/publishReindexRecords.json
- src/main/java/org/folio/persist/InstanceRepository.java
- src/main/java/org/folio/rest/impl/InventoryReindexRecordsPublishApi.java
- src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java
- src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java
- src/test/java/org/folio/rest/impl/InventoryReindexRecordsPublishIT.java
Correct "holdings" type naming
MODINVSTOR-1230
> fix(inventory-reindex-records): fix holdings type naming in reindex endpoint

- src/main/java/org/folio/services/domainevent/HoldingDomainEventPublisher.java
- src/main/java/org/folio/services/domainevent/InstanceDomainEventPublisher.java
- src/main/java/org/folio/services/domainevent/ItemDomainEventPublisher.java
Still publish event if no records in range exists
> fix(inventory-reindex-records): still publish event if no records

- src/main/resources/templates/db_scripts/schema.json
Fix deploy issue: https://folio-org.atlassian.net/browse/MODINVSTOR-1269
Change script order
> fix: change sql script order

- ramls/instance.json
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/PublicationPeriodMigrationTest.java
Temporary revert changes related to publication period migration as it takes too much time on big dataset
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._
> fix: revert changes related to publication period migration

- NEWS.md
- pom.xml
Prepare for 28.1.0 development iteration
> Prepare for 28.1.0 development iteration

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/createIndexBarcodePattern.sql
- src/main/resources/templates/db_scripts/schema.json
Purpose
Release v28.0.3, prepare v28.0.4 development iteration
Related Issue
[MODINVSTOR-1292](https://folio-org.atlassian.net/browse/MODINVSTOR-1292)
> Release v28.0.3, prepare v28.0.4 development iteration

- src/main/resources/templates/db_scripts/schema.json
Populate discovery suppress after mod-inventory fix https://folio-org.atlassian.net/browse/MODINV-1136
Move populateDiscoverySuppressIfNotSet.sql script into Q release
> [MODINVSTOR-1347] Move populateDiscoverySuppressIfNotSet.sql script into Q release

- src/main/resources/templates/db_scripts/schema.json
Run populateDiscoverySuppressIfNotSet.sql into R release
Move populateDiscoverySuppressIfNotSet.sql script into R release
> [MODINVSTOR-1348] Move populateDiscoverySuppressIfNotSet.sql script into R release

- NEWS.md
- pom.xml
prepare for next development iteration v29.1.0
> chore: prepare for next development iteration v29.1.0

- NEWS.md
- src/main/resources/templates/db_scripts/inventory-hierarchy/fixElectronicAccessOrder.sql
- src/main/resources/templates/db_scripts/schema.json
- src/test/java/org/folio/rest/api/InventoryHierarchyViewTest.java
- src/test/java/org/folio/rest/api/OaiPmhViewTest.java
- src/test/java/org/folio/rest/api/TestBaseWithInventoryUtil.java
- src/test/java/org/folio/rest/support/builders/HoldingRequestBuilder.java
Fix ordering of electronic access items for inventory-hierarchy, oai-pmh-view
Remove distinct statement in `getElectronicAccessName(val jsonb)` function
[MODINVSTOR-1224](https://folio-org.atlassian.net/browse/MODINVSTOR-1224)
> fix(electronic-access): Fix ordering of electronic access items for inventory-hierarchy, oai-pmh-view

- pom.xml
Fix build
update aspectj-maven-plugin release to 21
https://folio-org.atlassian.net/browse/MODINVSTOR-1374
> build: update aspectj-maven-plugin release to 21

- NEWS.md
- descriptors/ModuleDescriptor-template.json
- pom.xml
- ramls/item-storage.raml
- src/main/java/org/folio/rest/impl/ItemStorageApi.java
- src/test/java/org/folio/rest/api/ItemStorageTest.java
_Describe the purpose of this pull request. Why is this change necessary? What problem does it solve?_
https://folio-org.atlassian.net/browse/MODINVSTOR-1381
Corresponding mod-inventory PR: https://github.com/folio-org/mod-inventory/pull/825
_How does this change fulfill the purpose? Provide a high-level overview of the technical approach taken to address the problem._
> MODINVSTOR-1381: added post api to fetch inventory item

- NEWS.md
- src/main/java/org/folio/persist/InstanceRepository.java
- src/main/java/org/folio/services/instance/InstanceService.java
Optimize reindex instances database fetch query
[MODINVSTOR-1395](https://folio-org.atlassian.net/browse/MODINVSTOR-1395)
> feat(inventory-reindex-records): Optimize reindex instances database fetch query

- NEWS.md
- pom.xml
Release v28.0.11, prepare v28.0.12 development iteration
[MODINVSTOR-1398](https://folio-org.atlassian.net/browse/MODINVSTOR-1398)
[MODINVSTOR-1395](https://folio-org.atlassian.net/browse/MODINVSTOR-1395)
> Release v28.0.11, prepare v28.0.12 development iteration

- NEWS.md
- src/main/resources/templates/db_scripts/oaipmh/createDeletedIndex.sql
- src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-1421](https://folio-org.atlassian.net/browse/MODINVSTOR-1421)
Create index for "deleted" flag to improve performance of view get_instances_with_marc_records_deleted
Create index on "deleted" jsonb field.
[MODOAIPMH-614](https://folio-org.atlassian.net/browse/MODOAIPMH-614)
[MODOAIPMH-613](https://folio-org.atlassian.net/browse/MODOAIPMH-613)
> MODINVSTOR-1421 - Create index for "deleted" flag to improve performance of view get_instances_with_marc_records_deleted

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/oaipmh/createDeletedIndex.sql
- src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-1420](https://folio-org.atlassian.net/browse/MODINVSTOR-1420) - Release 29.0.8 (Sunflower)
Release v29.0.8
> Release v29.0.8

- NEWS.md
- src/main/resources/templates/db_scripts/oaipmh/addMigrationToUpdateDeleted.sql
- src/main/resources/templates/db_scripts/schema.json
[MODINVSTOR-1425](https://folio-org.atlassian.net/browse/MODINVSTOR-1425) - Execute migration script to add "deleted" field to instance.jsonb if it's missing
Execute migration script to add "deleted" field to instance.jsonb if it's missing.
> MODINVSTOR-1425 - Execute migration script to add "deleted" field to instance.jsonb if it's missing

- NEWS.md
- src/test/java/org/folio/rest/api/PrecedingSucceedingTitleMigrationScriptTest.java
Stabilize `canMigratePrecedingSucceedingTitles` test by searching title in the result list first
https://folio-org.atlassian.net/browse/MODINVSTOR-1407
> test: stabilize `canMigratePrecedingSucceedingTitles` test by searching title in the result list first

- NEWS.md
- docker/.env
- src/test/java/org/folio/rest/InstallUpgradeIT.java
- src/test/java/org/folio/rest/impl/BaseIntegrationTest.java
Stabilize tests by increasing the number of attempts to start the Kafka container
https://folio-org.atlassian.net/browse/MODINVSTOR-1413
> test: stabilize tests by increasing the number of attempts to start the Kafka container

- NEWS.md
- src/main/resources/templates/db_scripts/updateIdentifierTypeCanceledLCCN.sql
updateIdentifierTypeCanceledLCCN migration script to modify unexpected records
https://folio-org.atlassian.net/browse/MODINVSTOR-1361
> fix(migration): updateIdentifierTypeCanceledLCCN migration script to modify unexpected records

- NEWS.md
- pom.xml
- src/main/resources/templates/db_scripts/oaipmh/addMigrationToUpdateDeleted.sql
- src/main/resources/templates/db_scripts/schema.json
> Release v29.0.12

- NEWS.md
- src/main/java/org/folio/persist/AbstractRepository.java
- src/main/java/org/folio/services/migration/MigrationName.java
- src/main/java/org/folio/services/migration/async/AsyncMigrationJobService.java
- src/main/java/org/folio/services/migration/async/AsyncMigrationsConsumerUtils.java
- src/main/java/org/folio/services/migration/async/ItemOrderMigrationJobRunner.java
- src/main/java/org/folio/services/migration/async/ItemOrderMigrationService.java
- src/test/java/org/folio/rest/api/AsyncMigrationTest.java
- src/test/java/org/folio/services/migration/async/ItemOrderMigrationJobRunnerTest.java
- src/test/java/org/folio/services/migration/async/ItemOrderMigrationServiceTest.java
Implement async migration that will populate the item's order field
https://folio-org.atlassian.net/browse/MODINVSTOR-1442
> feat(item-storage): implement async migration that will populate the item's order field
